/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getApplyChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-apply-change',
    description: 'Implement tasks from an OpenSpec change. Use when the user wants to start implementing, continue implementation, or work through tasks.',
    instructions: `Implement tasks from an OpenSpec change.

**Input**: Optionally specify a change name. If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **Select the change**

   If a name is provided, use it. Otherwise resolve via:
   \`\`\`bash
   openspec agent resolve-change --auto
   \`\`\`
   - Exits 0 with the change name when exactly one active change exists.
   - Exits 1 (none) or 3 (ambiguous). On ambiguity, run \`openspec agent resolve-change --json\` and use the **AskUserQuestion tool** to let the user select.

   Always announce: "Using change: <name>" and how to override (e.g., \`/opsx:apply <other>\`).

2. **Load apply context (status + tasks + instruction in one call)**
   \`\`\`bash
   openspec instructions apply --change "<name>" --json
   \`\`\`

   Use the returned JSON:
   - \`schemaName\`: the workflow being used (e.g., "spec-driven")
   - \`contextFiles\`: artifact ID → array of file paths (varies by schema — proposal/specs/design/tasks for spec-driven)
   - \`progress\` (total / complete / remaining), \`tasks\` (with \`numericId\` when the file uses numbered tasks), \`nextPendingId\` (the first unchecked task with a \`numericId\`)
   - \`state\`: \`"blocked"\` (missing artifacts → suggest openspec-continue-change), \`"all_done"\` (congratulate, suggest archive), or \`"ready"\` (proceed)
   - \`instruction\`: dynamic guidance based on current state

   **Workspace guard:** If \`openspec status --change "<name>" --json\` reports \`actionContext.mode: "workspace-planning"\` and \`allowedEditRoots\` is empty, explain that full workspace apply is not supported in this slice. Treat linked repos and folders as read-only context, ask the user to select an affected area through an explicit implementation workflow, and STOP before editing files.

3. **Read context files**

   Read every file path listed under \`contextFiles\`.

4. **Show current progress**

   Display schema, "N/M tasks complete", remaining tasks overview, and the dynamic \`instruction\`.

5. **Implement tasks (loop until done or blocked)**

   For each pending task (drive by \`nextPendingId\`, or by document order for non-numeric tasks):
   - Show which task is being worked on
   - Make the code changes required (keep changes minimal and focused)
   - Mark the task complete via the CLI — idempotent, anchored on the task id so \`1.1\` does not match \`1.10\`:
     \`\`\`bash
     openspec agent mark-task-done --change "<name>" "<task-id>"
     \`\`\`
     where \`<task-id>\` is the task's \`numericId\` (e.g., \`1.1\`). For tasks without a \`numericId\`, edit the file directly (\`- [ ]\` → \`- [x]\`).
   - Re-run \`openspec instructions apply --change "<name>" --json\` to refresh \`nextPendingId\` and continue.

   **Pause if:**
   - Task is unclear → ask for clarification
   - Implementation reveals a design issue → suggest updating artifacts
   - Error or blocker encountered → report and wait for guidance
   - User interrupts

6. **On completion or pause, show status**

   Display:
   - Tasks completed this session
   - Overall progress: "N/M tasks complete"
   - If all done: suggest archive
   - If paused: explain why and wait for guidance

**Output During Implementation**

\`\`\`
## Implementing: <change-name> (schema: <schema-name>)

Working on task 3/7: <task description>
[...implementation happening...]
✓ Task complete

Working on task 4/7: <task description>
[...implementation happening...]
✓ Task complete
\`\`\`

**Output On Completion**

\`\`\`
## Implementation Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Progress:** 7/7 tasks complete ✓

### Completed This Session
- [x] Task 1
- [x] Task 2
...

All tasks complete! Ready to archive this change.
\`\`\`

**Output On Pause (Issue Encountered)**

\`\`\`
## Implementation Paused

**Change:** <change-name>
**Schema:** <schema-name>
**Progress:** 4/7 tasks complete

### Issue Encountered
<description of the issue>

**Options:**
1. <option 1>
2. <option 2>
3. Other approach

What would you like to do?
\`\`\`

**Guardrails**
- Keep going through tasks until done or blocked
- Always read context files before starting (from the apply instructions output)
- If task is ambiguous, pause and ask before implementing
- If implementation reveals issues, pause and suggest artifact updates
- Keep code changes minimal and scoped to each task
- Update task checkbox immediately after completing each task
- Pause on errors, blockers, or unclear requirements - don't guess
- Use contextFiles from CLI output, don't assume specific file names

**Fluid Workflow Integration**

This skill supports the "actions on a change" model:

- **Can be invoked anytime**: Before all artifacts are done (if tasks exist), after partial implementation, interleaved with other actions
- **Allows artifact updates**: If implementation reveals design issues, suggest updating artifacts - not phase-locked, work fluidly`,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxApplyCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Apply',
    description: 'Implement tasks from an OpenSpec change (Experimental)',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `Implement tasks from an OpenSpec change.

**Input**: Optionally specify a change name (e.g., \`/opsx:apply add-auth\`). If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **Select the change**

   If a name is provided, use it. Otherwise resolve via:
   \`\`\`bash
   openspec agent resolve-change --auto
   \`\`\`
   - Exits 0 with the change name when exactly one active change exists.
   - Exits 1 (none) or 3 (ambiguous). On ambiguity, run \`openspec agent resolve-change --json\` and use the **AskUserQuestion tool** to let the user select.

   Always announce: "Using change: <name>" and how to override (e.g., \`/opsx:apply <other>\`).

2. **Load apply context (status + tasks + instruction in one call)**
   \`\`\`bash
   openspec instructions apply --change "<name>" --json
   \`\`\`

   Use the returned JSON:
   - \`schemaName\`: the workflow being used (e.g., "spec-driven")
   - \`contextFiles\`: artifact ID → array of file paths (varies by schema)
   - \`progress\` (total / complete / remaining), \`tasks\` (with \`numericId\` when the file uses numbered tasks), \`nextPendingId\` (the first unchecked task with a \`numericId\`)
   - \`state\`: \`"blocked"\` (missing artifacts → suggest \`/opsx:continue\`), \`"all_done"\` (congratulate, suggest archive), or \`"ready"\` (proceed)
   - \`instruction\`: dynamic guidance based on current state

   **Workspace guard:** If \`openspec status --change "<name>" --json\` reports \`actionContext.mode: "workspace-planning"\` and \`allowedEditRoots\` is empty, explain that full workspace apply is not supported in this slice. Treat linked repos and folders as read-only context, ask the user to select an affected area through an explicit implementation workflow, and STOP before editing files.

3. **Read context files**

   Read every file path listed under \`contextFiles\`.

4. **Show current progress**

   Display schema, "N/M tasks complete", remaining tasks overview, and the dynamic \`instruction\`.

5. **Implement tasks (loop until done or blocked)**

   For each pending task (drive by \`nextPendingId\`, or by document order for non-numeric tasks):
   - Show which task is being worked on
   - Make the code changes required (keep changes minimal and focused)
   - Mark the task complete via the CLI — idempotent, anchored on the task id so \`1.1\` does not match \`1.10\`:
     \`\`\`bash
     openspec agent mark-task-done --change "<name>" "<task-id>"
     \`\`\`
     where \`<task-id>\` is the task's \`numericId\` (e.g., \`1.1\`). For tasks without a \`numericId\`, edit the file directly (\`- [ ]\` → \`- [x]\`).
   - Re-run \`openspec instructions apply --change "<name>" --json\` to refresh \`nextPendingId\` and continue.

   **Pause if:**
   - Task is unclear → ask for clarification
   - Implementation reveals a design issue → suggest updating artifacts
   - Error or blocker encountered → report and wait for guidance
   - User interrupts

6. **On completion or pause, show status**

   Display:
   - Tasks completed this session
   - Overall progress: "N/M tasks complete"
   - If all done: suggest archive
   - If paused: explain why and wait for guidance

**Output During Implementation**

\`\`\`
## Implementing: <change-name> (schema: <schema-name>)

Working on task 3/7: <task description>
[...implementation happening...]
✓ Task complete

Working on task 4/7: <task description>
[...implementation happening...]
✓ Task complete
\`\`\`

**Output On Completion**

\`\`\`
## Implementation Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Progress:** 7/7 tasks complete ✓

### Completed This Session
- [x] Task 1
- [x] Task 2
...

All tasks complete! You can archive this change with \`/opsx:archive\`.
\`\`\`

**Output On Pause (Issue Encountered)**

\`\`\`
## Implementation Paused

**Change:** <change-name>
**Schema:** <schema-name>
**Progress:** 4/7 tasks complete

### Issue Encountered
<description of the issue>

**Options:**
1. <option 1>
2. <option 2>
3. Other approach

What would you like to do?
\`\`\`

**Guardrails**
- Keep going through tasks until done or blocked
- Always read context files before starting (from the apply instructions output)
- If task is ambiguous, pause and ask before implementing
- If implementation reveals issues, pause and suggest artifact updates
- Keep code changes minimal and scoped to each task
- Update task checkbox immediately after completing each task
- Pause on errors, blockers, or unclear requirements - don't guess
- Use contextFiles from CLI output, don't assume specific file names

**Fluid Workflow Integration**

This skill supports the "actions on a change" model:

- **Can be invoked anytime**: Before all artifacts are done (if tasks exist), after partial implementation, interleaved with other actions
- **Allows artifact updates**: If implementation reveals design issues, suggest updating artifacts - not phase-locked, work fluidly`
  };
}
