/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getApplyChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'pastelsdd-apply-change',
    description: 'Implement tasks from an Pastelsdd change. Use when the user wants to start implementing, continue implementation, or work through tasks.',
    instructions: getApplyInstructions(),
    license: 'MIT',
    compatibility: 'Requires pastelsdd CLI.',
    metadata: { author: 'pastelsdd', version: '1.0' },
  };
}

export function getPastelApplyCommandTemplate(): CommandTemplate {
  return {
    name: 'Pastel: Apply',
    description: 'Implement tasks from a Pastelsdd change',
    category: 'Workflow',
    tags: ['workflow', 'apply', 'implementation'],
    content: getApplyInstructions(),
  };
}

function getApplyInstructions(): string {
  return `Implement tasks from a Pastelsdd change.

**Input**: Optionally specify a change name (e.g., \`/pstl:apply add-auth\`). If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **Select the change**

   If a name is provided, use it. Otherwise:
   - Infer from conversation context if the user mentioned a change
   - Auto-select if only one active change exists
   - If ambiguous, run \`pastelsdd list --json\` to get available changes and use the **AskUserQuestion tool** to let the user select

   Always announce: "Using change: <name>" and how to override (e.g., \`/pstl:apply <other>\`).

2. **Check status to understand the schema**
   \`\`\`bash
   pastelsdd status --change "<name>" --json
   \`\`\`
   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used (e.g., "spec-driven")
   - \`planningHome\`, \`changeRoot\`, and \`actionContext\`: planning scope and edit constraints
   - Which artifact contains the tasks (typically "tasks" for spec-driven, check status for others)

3. **Get apply instructions**

   \`\`\`bash
   pastelsdd instructions apply --change "<name>" --json
   \`\`\`

   This returns:
   - \`contextFiles\`: artifact ID -> array of concrete file paths (varies by schema)
   - Progress (total, complete, remaining)
   - Task list with status
   - Dynamic instruction based on current state

   **Handle states:**
   - If \`state: "blocked"\` (missing artifacts): show message, suggest using \`/pstl:continue\`
   - If \`state: "all_done"\`: congratulate, suggest archive
   - Otherwise: proceed to implementation

   **Workspace guard:** If status JSON reports \`actionContext.mode: "workspace-planning"\` and \`allowedEditRoots\` is empty, explain that full workspace apply is not supported in this slice. Treat linked repos and folders as read-only context, ask the user to select an affected area, and STOP before editing files.

4. **Read context files**

   Read every file path listed under \`contextFiles\` from the apply instructions output.

5. **Show current progress**

   Display:
   - Schema being used
   - Progress: "N/M tasks complete"
   - Remaining tasks overview
   - Dynamic instruction from CLI

6. **Trello Integration — move card to "Em Desenvolvimento" (optional)**

   Use the **Read tool** (NOT a shell command) to read \`pastelsdd/trello.yaml\` from the current working directory.
   The Read tool is cross-platform and works on Windows, macOS, and Linux — never use \`cat\` or shell commands to read this file.
   If the Read tool returns an error (file not found), skip all Trello steps.

   Otherwise parse and extract \`boardId\`, \`lists.refining\`, \`lists.ready\`, \`lists.developing\`, and \`lists.testing\`.

   Search for the change's card across configured lists in priority order:
   \`refining\` → \`ready\` → \`backlog\` (whichever are configured):
   \`\`\`tool
   mcp__claude_ai_Trello_Custom__get_cards  { list_id: "<list.id>" }
   \`\`\`
   Look for a card matching the change name (case-insensitive, partial match is sufficient).

   **If \`lists.developing\` is configured:**
   - **Card found:** move it to \`lists.developing\`.
   - **No card found:** create one directly in \`lists.developing\` with name and desc in Portuguese.

   **If \`lists.developing\` is NOT configured and \`lists.ready\` is configured:**
   - Move/create in \`lists.ready\`.

   In all cases, assign the current user:
   \`\`\`tool
   mcp__claude_ai_Trello_Custom__get_me
   mcp__claude_ai_Trello_Custom__add_card_member  { card_id: "<cardId>", member_id: "<me.id>" }
   \`\`\`
   Save \`cardId\` for the completion step.

   If any Trello call fails, continue — Trello is auxiliary, never blocking.

7. **Implement tasks (loop until done or blocked)**

   For each pending task:
   - Show which task is being worked on
   - Make the code changes required
   - Keep changes minimal and focused
   - Mark task complete in the tasks file: \`- [ ]\` → \`- [x]\`
   - Continue to next task

   **Pause if:**
   - Task is unclear → ask for clarification
   - Implementation reveals a design issue → suggest updating artifacts
   - Error or blocker encountered → report and wait for guidance
   - User interrupts

8. **On completion: move card to "Em Teste" (optional)**

   When all tasks are complete (\`state: "all_done"\`):

   If Trello is configured and \`cardId\` was saved:

   a. If \`lists.testing\` is configured, move the card there:
      \`\`\`tool
      mcp__claude_ai_Trello_Custom__update_card  { card_id: "<cardId>", list_id: "<lists.testing.id>" }
      \`\`\`

   b. Add a comment in Portuguese:
      \`\`\`tool
      mcp__claude_ai_Trello_Custom__add_comment
        card_id: "<cardId>"
        text: |
          Implementacao concluida via /pstl:apply

          Change: <change-name>
          Tasks: <N>/<N> concluidas

          Proximo passo: /pstl:archive <name> para arquivar a change.
      \`\`\`

9. **On completion or pause, show status**

   Display:
   - Tasks completed this session
   - Overall progress: "N/M tasks complete"
   - If all done: suggest \`/pstl:archive\` + mention Trello card stage if applicable
   - If paused: explain why and wait for guidance

**Output During Implementation**

\`\`\`
## Implementing: <change-name> (schema: <schema-name>)

Working on task 3/7: <task description>
[...implementation happening...]
✓ Task complete

Working on task 4/7: <task description>
[...implementation happening...]
✓ Task complete
\`\`\`

**Output On Completion**

\`\`\`
## Implementation Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Progress:** 7/7 tasks complete ✓
**Trello:** Card moved to 🧪 Em Teste        ← only shown if Trello is configured

### Completed This Session
- [x] Task 1
- [x] Task 2
...

All tasks complete! Archive with \`/pstl:archive\`.
\`\`\`

**Output On Pause (Issue Encountered)**

\`\`\`
## Implementation Paused

**Change:** <change-name>
**Schema:** <schema-name>
**Progress:** 4/7 tasks complete

### Issue Encountered
<description of the issue>

**Options:**
1. <option 1>
2. <option 2>
3. Other approach

What would you like to do?
\`\`\`

**Guardrails**
- Keep going through tasks until done or blocked
- Always read context files before starting
- If task is ambiguous, pause and ask before implementing
- If implementation reveals issues, pause and suggest artifact updates
- Keep code changes minimal and scoped to each task
- Update task checkbox immediately after completing each task
- Pause on errors, blockers, or unclear requirements — don't guess
- Use contextFiles from CLI output, don't assume specific file names
- If Trello tools fail, continue normally — Trello is auxiliary, not blocking
- All content written to Trello must be in Portuguese

**Fluid Workflow Integration**

- **Can be invoked anytime**: Before all artifacts are done (if tasks exist), after partial implementation
- **Allows artifact updates**: If implementation reveals design issues, suggest updating artifacts
`;
}
