/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { STORE_SELECTION_GUIDANCE } from './store-selection.js';

export function getArchiveChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-archive-change',
    description: 'Archive a completed change in the experimental workflow. Use when the user wants to finalize and archive a change after implementation is complete.',
    instructions: `Archive a completed change in the experimental workflow.

${STORE_SELECTION_GUIDANCE}

**Input**: Optionally specify a change name. If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **If no change name provided, prompt for selection**

   Run \`openspec list --json\` to get available changes. Use the **AskUserQuestion tool** to let the user select.

   Show only active changes (not already archived).
   Include the schema used for each change if available.

   **IMPORTANT**: Do NOT guess or auto-select a change. Always let the user choose.

2. **Check artifact completion status**

   Run \`openspec status --change "<name>" --json\` to check artifact completion.

   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used
   - \`planningHome\`, \`changeRoot\`, \`artifactPaths\`, and \`actionContext\`: path and scope context
   - \`artifacts\`: List of artifacts with their status (\`done\` or other)

   **If any artifacts are not \`done\`:**
   - Display warning listing incomplete artifacts
   - Use **AskUserQuestion tool** to confirm user wants to proceed
   - Proceed if user confirms

3. **Check task completion status**

   Read the tasks file (typically \`tasks.md\`) to check for incomplete tasks.

   Count tasks marked with \`- [ ]\` (incomplete) vs \`- [x]\` (complete).

   **If incomplete tasks found:**
   - Display warning showing count of incomplete tasks
   - Use **AskUserQuestion tool** to confirm user wants to proceed
   - Proceed if user confirms

   **If no tasks file exists:** Proceed without task-related warning.

4. **Archive via the \`openspec archive\` CLI**

   Run the archive through the CLI — it deterministically validates the change, syncs delta specs into \`openspec/specs/\`, and moves the change to the archive folder. Do NOT assess sync state yourself, move files, or merge specs by hand:
   \`\`\`bash
   openspec archive "<name>" --json --yes
   \`\`\`

   - **On success**: the JSON result includes \`archivedAs\`, \`path\`, and \`specsUpdated\` (with add/modify/remove/rename totals when specs were synced). Use these for the summary.
   - **On a block** (non-zero exit with a \`status\` diagnostic): the change was NOT archived and nothing was moved. Surface the diagnostic, fix the cause, then re-run \`openspec archive\`:
     - Missing or partial delta specs, or a spec written as a full spec (\`## Purpose\`/\`## Requirements\`) instead of a delta (\`## ADDED/MODIFIED/REMOVED/RENAMED Requirements\`): create or fix the delta spec at \`changes/<name>/specs/<capability>/spec.md\`.
     - Incomplete tasks: complete them, or re-run only if the user confirms.
   - Do NOT bypass a validation block with \`--skip-specs\` or \`--no-validate\`. Use \`--skip-specs\` only when the user explicitly confirms the change has no specs to sync. Trust the CLI's exit status; never self-certify that specs are synced.

5. **Display summary**

   Show archive completion summary including:
   - Change name
   - Schema that was used
   - Archive location
   - Whether specs were synced (if applicable)
   - Note about any warnings (incomplete artifacts/tasks)

**Output On Success**

\`\`\`
## Archive Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** the archive path derived from \`planningHome.changesDir\`/YYYY-MM-DD-<name>/
**Specs:** ✓ Synced to main specs (or "No delta specs" or "Sync skipped")

All artifacts complete. All tasks complete.
\`\`\`

**Guardrails**
- Always prompt for change selection if not provided
- Use artifact graph (openspec status --json) for completion checking
- Don't block archive on warnings - just inform and confirm
- Preserve .openspec.yaml when moving to archive (it moves with the directory)
- Show clear summary of what happened
- Archive only via \`openspec archive\`; never move the change with \`mv\` or merge specs yourself
- Never bypass a validation block with \`--skip-specs\`/\`--no-validate\`; on a block, fix the delta spec and re-run \`openspec archive\``,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxArchiveCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Archive',
    description: 'Archive a completed change in the experimental workflow',
    category: 'Workflow',
    tags: ['workflow', 'archive', 'experimental'],
    content: `Archive a completed change in the experimental workflow.

${STORE_SELECTION_GUIDANCE}

**Input**: Optionally specify a change name after \`/opsx:archive\` (e.g., \`/opsx:archive add-auth\`). If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **If no change name provided, prompt for selection**

   Run \`openspec list --json\` to get available changes. Use the **AskUserQuestion tool** to let the user select.

   Show only active changes (not already archived).
   Include the schema used for each change if available.

   **IMPORTANT**: Do NOT guess or auto-select a change. Always let the user choose.

2. **Check artifact completion status**

   Run \`openspec status --change "<name>" --json\` to check artifact completion.

   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used
   - \`planningHome\`, \`changeRoot\`, \`artifactPaths\`, and \`actionContext\`: path and scope context
   - \`artifacts\`: List of artifacts with their status (\`done\` or other)

   **If any artifacts are not \`done\`:**
   - Display warning listing incomplete artifacts
   - Prompt user for confirmation to continue
   - Proceed if user confirms

3. **Check task completion status**

   Read the tasks file (typically \`tasks.md\`) to check for incomplete tasks.

   Count tasks marked with \`- [ ]\` (incomplete) vs \`- [x]\` (complete).

   **If incomplete tasks found:**
   - Display warning showing count of incomplete tasks
   - Prompt user for confirmation to continue
   - Proceed if user confirms

   **If no tasks file exists:** Proceed without task-related warning.

4. **Archive via the \`openspec archive\` CLI**

   Run the archive through the CLI — it deterministically validates the change, syncs delta specs into \`openspec/specs/\`, and moves the change to the archive folder. Do NOT assess sync state yourself, move files, or merge specs by hand:
   \`\`\`bash
   openspec archive "<name>" --json --yes
   \`\`\`

   - **On success**: the JSON result includes \`archivedAs\`, \`path\`, and \`specsUpdated\` (with add/modify/remove/rename totals when specs were synced). Use these for the summary.
   - **On a block** (non-zero exit with a \`status\` diagnostic): the change was NOT archived and nothing was moved. Surface the diagnostic, fix the cause, then re-run \`openspec archive\`:
     - Missing or partial delta specs, or a spec written as a full spec (\`## Purpose\`/\`## Requirements\`) instead of a delta (\`## ADDED/MODIFIED/REMOVED/RENAMED Requirements\`): create or fix the delta spec at \`changes/<name>/specs/<capability>/spec.md\`.
     - Incomplete tasks: complete them, or re-run only if the user confirms.
   - Do NOT bypass a validation block with \`--skip-specs\` or \`--no-validate\`. Use \`--skip-specs\` only when the user explicitly confirms the change has no specs to sync. Trust the CLI's exit status; never self-certify that specs are synced.

5. **Display summary**

   Show archive completion summary including:
   - Change name
   - Schema that was used
   - Archive location
   - Spec sync status (synced / sync skipped / no delta specs)
   - Note about any warnings (incomplete artifacts/tasks)

**Output On Success**

\`\`\`
## Archive Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** the archive path derived from \`planningHome.changesDir\`/YYYY-MM-DD-<name>/
**Specs:** ✓ Synced to main specs

All artifacts complete. All tasks complete.
\`\`\`

**Output On Success (No Delta Specs)**

\`\`\`
## Archive Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** the archive path derived from \`planningHome.changesDir\`/YYYY-MM-DD-<name>/
**Specs:** No delta specs

All artifacts complete. All tasks complete.
\`\`\`

**Output On Success With Warnings**

\`\`\`
## Archive Complete (with warnings)

**Change:** <change-name>
**Schema:** <schema-name>
**Archived to:** the archive path derived from \`planningHome.changesDir\`/YYYY-MM-DD-<name>/
**Specs:** Sync skipped (user chose to skip)

**Warnings:**
- Archived with 2 incomplete artifacts
- Archived with 3 incomplete tasks
- Delta spec sync was skipped (user chose to skip)

Review the archive if this was not intentional.
\`\`\`

**Output On Error (Archive Exists)**

\`\`\`
## Archive Failed

**Change:** <change-name>
**Target:** the archive path derived from \`planningHome.changesDir\`/YYYY-MM-DD-<name>/

Target archive directory already exists.

**Options:**
1. Rename the existing archive
2. Delete the existing archive if it's a duplicate
3. Wait until a different date to archive
\`\`\`

**Guardrails**
- Always prompt for change selection if not provided
- Use artifact graph (openspec status --json) for completion checking
- Don't block archive on warnings - just inform and confirm
- Preserve .openspec.yaml when moving to archive (it moves with the directory)
- Show clear summary of what happened
- Archive only via \`openspec archive\`; never move the change with \`mv\` or merge specs yourself
- Never bypass a validation block with \`--skip-specs\`/\`--no-validate\`; on a block, fix the delta spec and re-run \`openspec archive\``
  };
}
