/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { STORE_SELECTION_GUIDANCE } from './store-selection.js';

const BRIEF_INSTRUCTIONS = `Generate a one-page HTML brief for an OpenSpec change.

${STORE_SELECTION_GUIDANCE}

**Input**: Optionally specify a change name. If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **Select the change**

   If a name is provided, use it. Otherwise:
   - Infer from conversation context if the user mentioned a change
   - Auto-select if only one active change exists
   - If ambiguous, run \`openspec list --json\` to get available changes and ask the user to select from the available changes

   Always announce: "Using change: <name>" and how to override (e.g., \`/opsx:brief <other>\`).

2. **Check status and planning context**
   \`\`\`bash
   openspec status --change "<name>" --json
   \`\`\`
   Parse the JSON to understand:
   - \`schemaName\`: The workflow schema being used
   - \`planningHome\`, \`changeRoot\`, \`artifactPaths\`, and \`actionContext\`: path and scope context
   - Which artifacts exist or are missing

3. **Get artifact context**
   \`\`\`bash
   openspec instructions apply --change "<name>" --json
   \`\`\`

   This returns:
   - \`changeDir\`: concrete change directory
   - \`contextFiles\`: artifact ID -> array of concrete file paths
   - \`progress\`, \`tasks\`, \`state\`, and \`instruction\`

   If the apply instructions report missing artifacts, continue with available artifacts and call out the missing information in the brief.

4. **Read source artifacts**

   Read every file path listed under \`contextFiles\`. Common artifacts include:
   - \`proposal\`: what and why
   - \`specs\`: normative requirement deltas
   - \`design\`: decisions, trade-offs, risks
   - \`tasks\`: implementation order and verification hints

   Use the CLI-provided paths. Do not assume repo-local \`openspec/changes/<name>\` paths when \`changeDir\` or \`planningHome\` provides a concrete path.

5. **Synthesize the brief**

   Create a concise, human-readable review surface. The brief should help a user understand the change in about 3 minutes without reading every artifact.

   Before writing HTML, build a short internal outline from the artifacts:
   - Source artifact index: every file path returned in \`contextFiles\`, grouped by artifact ID
   - Delta spec coverage: every spec file from \`contextFiles.specs\`
   - Task coverage: task groups aligned with the numbered headings in the tasks artifact; if tasks are summarized, say so
   - Impact list: affected modules or file areas stated by the artifacts; mark inferred impacts as "Inference"

   Include these sections:
   - What this change does
   - Explicit non-goals
   - User-visible behavior changes
   - Affected modules / file areas
   - Key design decisions and trade-offs
   - Implementation order
   - Testing and verification plan
   - Risks and questions requiring user confirmation
   - Source artifact index

   **Accuracy rules**
   - The original OpenSpec artifacts remain the source of truth. The brief is only a review surface.
   - Every substantive claim must include source attribution such as \`Source: proposal.md\`, \`Source: design.md\`, \`Source: specs/<capability>/spec.md\`, or \`Source: tasks.md\`.
   - The source artifact index must include every file path returned in \`contextFiles\`; do not silently drop delta specs or schema-specific artifacts.
   - If a section is not specified by the source artifacts, write "Not specified in source artifacts" instead of inventing content.
   - Separate direct source facts from your inference. Label inference as "Inference".
   - Do not turn non-goals into fallback plans or implied future work unless the source artifacts explicitly say so.
   - Do not add affected files, modules, user-visible behavior, risks, or questions unless they are sourced or clearly labeled as inference.
   - Keep the page concise. Prefer short bullets and compact tables over long prose.

6. **Write static HTML**

   Write the output to:
   \`\`\`text
   <changeDir>/brief.html
   \`\`\`

   The HTML must be:
   - standalone static HTML
   - no external JavaScript, CSS, fonts, images, CDN links, or network resources
   - use system fonts only; do not import Google Fonts or other remote fonts
   - professional and readable in a browser
   - generic to the current OpenSpec change; do not include unrelated product names, project names, footers, or branding unless they appear in the source artifacts
   - agent-agnostic; do not hardcode tool-specific paths or labels such as \`.codex\`, \`.agents\`, Claude, Codex, or any harness-specific implementation detail unless the source artifacts explicitly mention them
   - safe for artifact text: escape \`&\`, \`<\`, \`>\`, \`"\`, and \`'\` if you include source excerpts or user-provided content

   Use inline \`<style>\` only. Do not create additional files.

7. **Best-effort open**

   After writing \`brief.html\`, try to open it:
   - macOS: \`open "<path>"\`
   - Linux: \`xdg-open "<path>"\`
   - Windows PowerShell: \`Start-Process "<path>"\`

   If opening fails or is unavailable, do not treat that as failure. Print the generated file path clearly.

**Output**

After generating the brief, summarize:
- Change name
- Brief path
- Whether it was opened or opening was skipped/failed
- Any source artifacts that were missing
- Any questions requiring user confirmation

**Guardrails**
- Do not modify \`proposal.md\`, \`design.md\`, \`tasks.md\`, or \`specs/**/spec.md\`.
- Do not implement the change.
- Do not archive or sync specs.
- Do not claim the brief is authoritative.
- If the source artifacts conflict, show the conflict in the brief instead of resolving it silently.
- If the requested change does not exist, stop and show available changes.`;

export function getBriefChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-brief-change',
    description: 'Generate a one-page HTML brief for an OpenSpec change. Use when the user wants a concise, accurate review surface before implementation.',
    instructions: BRIEF_INSTRUCTIONS,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxBriefCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Brief',
    description: 'Generate a one-page HTML brief for an OpenSpec change',
    category: 'Workflow',
    tags: ['workflow', 'brief', 'review'],
    content: BRIEF_INSTRUCTIONS.replace(
      '**Input**: Optionally specify a change name.',
      '**Input**: Optionally specify a change name after `/opsx:brief` (e.g., `/opsx:brief add-auth`).'
    )
  };
}
