/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { STORE_SELECTION_GUIDANCE } from './store-selection.js';

const MANDATORY_DOMAIN_SELECTION_GUIDANCE = `3. **Select the domain (required)**

   **Domain selection is mandatory.** Ask the user which domain should contain the change, and recommend lowercase kebab-case domain segments (for example, \`payments/api\`). Root placement is an explicit choice represented by an empty domain.

   If the user provides a CLI-valid literal that does not follow the recommendation, **Do not silently transform it**. Present these choices:
   1. Convert to the suggested lowercase kebab-case value
   2. Keep the exact literal
   3. Choose another domain

   Build the conversion suggestion by replacing acronym/CamelCase boundaries sensibly (\`XMLParser\` -> \`xml-parser\`, \`IOError\` -> \`io-error\`), replace underscores with hyphens, and lowercase only after the user chooses conversion. Use the user's confirmed value as \`<resolved-domain>\`; use an empty string for root placement.`;

export function getNewChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-new-change',
    description: 'Start a new OpenSpec change using the experimental artifact workflow. Use when the user wants to create a new feature, fix, or modification with a structured step-by-step approach.',
    instructions: `Start a new change using the experimental artifact-driven approach.

${STORE_SELECTION_GUIDANCE}

**Input**: The user's request should include a change name (kebab-case) OR a description of what they want to build.

**Steps**

1. **If no clear input provided, ask what they want to build**

   Use the **AskUserQuestion tool** (open-ended, no preset options) to ask:
   > "What change do you want to work on? Describe what you want to build or fix."

   From their description, derive a kebab-case name (e.g., "add user authentication" → \`add-user-auth\`).

   **IMPORTANT**: Do NOT proceed without understanding what the user wants to build.

2. **Determine the workflow schema**

   Use the default schema (omit \`--schema\`) unless the user explicitly requests a different workflow.

   **Use a different schema only if the user mentions:**
   - A specific schema name → use \`--schema <name>\`
   - "show workflows" or "what workflows" → run \`openspec schemas --json\` and let them choose

   **Otherwise**: Omit \`--schema\` to use the default.

${MANDATORY_DOMAIN_SELECTION_GUIDANCE}

4. **Create the change directory**
   \`\`\`bash
   openspec new change "<name>" --domain "<resolved-domain>"
   \`\`\`
   For root placement, invoke \`openspec new change "<name>" --domain ""\`. If a store was selected, append \`--store <id>\` to either invocation.
   Set \`<change-id>\` to \`<resolved-domain>/<name>\` for a non-root domain, or \`<name>\` for root placement. Keep any selected \`--store <id>\` on every supported follow-up command.
   Add \`--schema <name>\` only if the user requested a specific workflow.
   This creates a scaffolded change in the planning home resolved by the CLI.

5. **Show the artifact status**
   \`\`\`bash
   openspec status --change "<change-id>" --json
   \`\`\`
   Use the returned \`planningHome\`, \`changeRoot\`, \`artifactPaths\`, and \`nextSteps\` instead of assuming repo-local paths.

6. **Get instructions for the first artifact**
   The first artifact depends on the schema (e.g., \`proposal\` for spec-driven).
   Check the status output to find the first artifact with status "ready".
   \`\`\`bash
   openspec instructions <first-artifact-id> --change "<change-id>"
   \`\`\`
   This outputs the template and context for creating the first artifact.

7. **STOP and wait for user direction**

**Output**

After completing the steps, summarize:
- Change name and location
- Schema/workflow being used and its artifact sequence
- Current status (0/N artifacts complete)
- The template for the first artifact
- Prompt: "Ready to create the first artifact? Just describe what this change is about and I'll draft it, or ask me to continue."

**Guardrails**
- Do NOT create any artifacts yet - just show the instructions
- Do NOT advance beyond showing the first artifact template
- If the name is invalid (not kebab-case), ask for a valid name
- If a change with that name already exists, suggest continuing that change instead
- Pass --schema if using a non-default workflow`,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxNewCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: New',
    description: 'Start a new change using the experimental artifact workflow (OPSX)',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `Start a new change using the experimental artifact-driven approach.

${STORE_SELECTION_GUIDANCE}

**Input**: The argument after \`/opsx:new\` is the change name (kebab-case), OR a description of what the user wants to build.

**Steps**

1. **If no input provided, ask what they want to build**

   Use the **AskUserQuestion tool** (open-ended, no preset options) to ask:
   > "What change do you want to work on? Describe what you want to build or fix."

   From their description, derive a kebab-case name (e.g., "add user authentication" → \`add-user-auth\`).

   **IMPORTANT**: Do NOT proceed without understanding what the user wants to build.

2. **Determine the workflow schema**

   Use the default schema (omit \`--schema\`) unless the user explicitly requests a different workflow.

   **Use a different schema only if the user mentions:**
   - A specific schema name → use \`--schema <name>\`
   - "show workflows" or "what workflows" → run \`openspec schemas --json\` and let them choose

   **Otherwise**: Omit \`--schema\` to use the default.

${MANDATORY_DOMAIN_SELECTION_GUIDANCE}

4. **Create the change directory**
   \`\`\`bash
   openspec new change "<name>" --domain "<resolved-domain>"
   \`\`\`
   For root placement, invoke \`openspec new change "<name>" --domain ""\`. If a store was selected, append \`--store <id>\` to either invocation.
   Set \`<change-id>\` to \`<resolved-domain>/<name>\` for a non-root domain, or \`<name>\` for root placement. Keep any selected \`--store <id>\` on every supported follow-up command.
   Add \`--schema <name>\` only if the user requested a specific workflow.
   This creates a scaffolded change in the planning home resolved by the CLI.

5. **Show the artifact status**
   \`\`\`bash
   openspec status --change "<change-id>" --json
   \`\`\`
   Use the returned \`planningHome\`, \`changeRoot\`, \`artifactPaths\`, and \`nextSteps\` instead of assuming repo-local paths.

6. **Get instructions for the first artifact**
   The first artifact depends on the schema. Check the status output to find the first artifact with status "ready".
   \`\`\`bash
   openspec instructions <first-artifact-id> --change "<change-id>"
   \`\`\`
   This outputs the template and context for creating the first artifact.

7. **STOP and wait for user direction**

**Output**

After completing the steps, summarize:
- Change name and location
- Schema/workflow being used and its artifact sequence
- Current status (0/N artifacts complete)
- The template for the first artifact
- Prompt: "Ready to create the first artifact? Run \`/opsx:continue <change-id>\` or just describe what this change is about and I'll draft it."

**Guardrails**
- Do NOT create any artifacts yet - just show the instructions
- Do NOT advance beyond showing the first artifact template
- If the name is invalid (not kebab-case), ask for a valid name
- If a change with that ID already exists, suggest using \`/opsx:continue <change-id>\` instead
- Pass --schema if using a non-default workflow`
  };
}
