/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getOpsxProposeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-propose',
    description: 'Propose a new change with all artifacts generated in one step. Use when the user wants to quickly describe what they want to build and get a complete proposal with design, specs, and tasks ready for implementation.',
    instructions: `Propose a new change - create the change and generate all artifacts in one step.

I'll create a change with artifacts:
- proposal.md (what & why)
- design.md (how)
- tasks.md (implementation steps)

When ready to implement, run /opsx:apply

---

**Input**: The user's request should include a change name (kebab-case) OR a description of what they want to build.

**Steps**

1. **If no clear input provided, ask what they want to build**

   Use the **AskUserQuestion tool** (open-ended, no preset options) to ask:
   > "What change do you want to work on? Describe what you want to build or fix."

   From their description, derive a kebab-case name (e.g., "add user authentication" → \`add-user-auth\`).

   **IMPORTANT**: Do NOT proceed without understanding what the user wants to build.

2. **Create the change directory**
   \`\`\`bash
   openspec new change "<name>"
   \`\`\`
   This creates a scaffolded change in the planning home resolved by the CLI with \`.openspec.yaml\`.

3. **Drive the artifact loop with \`next-artifact\`**

   Use the **TodoWrite tool** to track progress.

   Repeat until \`{ "done": true }\`:
   \`\`\`bash
   openspec agent next-artifact --change "<name>"
   \`\`\`

   Each non-done response returns the JSON instructions payload for exactly one ready artifact:
   - \`artifactId\`, \`resolvedOutputPath\`: which file to write and where
   - \`template\`: the structure to use for your output (fill in its sections)
   - \`instruction\`: schema-specific guidance for this artifact type
   - \`context\`, \`rules\`: constraints for YOU — do NOT copy these into the file
   - \`dependencies\`: completed artifacts to read for context before writing

   For each response:
   1. Read any \`dependencies\` files for context
   2. Write the artifact file (use \`template\` as the structure, write to \`resolvedOutputPath\`)
   3. Show brief progress: "Created <artifact-id>"
   4. Re-invoke \`openspec agent next-artifact --change "<name>"\` and continue

   If an artifact requires user input (context unclear), use the **AskUserQuestion tool** to clarify, then continue.

4. **Show final status**
   \`\`\`bash
   openspec status --change "<name>"
   \`\`\`

**Output**

After completing all artifacts, summarize:
- Change name and location
- List of artifacts created with brief descriptions
- What's ready: "All artifacts created! Ready for implementation."
- Prompt: "Run \`/opsx:apply\` or ask me to implement to start working on the tasks."

**Artifact Creation Guidelines**

- Follow the \`instruction\` field from \`openspec instructions\` for each artifact type
- The schema defines what each artifact should contain - follow it
- Read dependency artifacts for context before creating new ones
- Use \`template\` as the structure for your output file - fill in its sections
- **IMPORTANT**: \`context\` and \`rules\` are constraints for YOU, not content for the file
  - Do NOT copy \`<context>\`, \`<rules>\`, \`<project_context>\` blocks into the artifact
  - These guide what you write, but should never appear in the output

**Guardrails**
- Create ALL artifacts needed for implementation (as defined by schema's \`apply.requires\`)
- Always read dependency artifacts before creating a new one
- If context is critically unclear, ask the user - but prefer making reasonable decisions to keep momentum
- If a change with that name already exists, ask if user wants to continue it or create a new one
- Verify each artifact file exists after writing before proceeding to next`,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxProposeCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Propose',
    description: 'Propose a new change - create it and generate all artifacts in one step',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: `Propose a new change - create the change and generate all artifacts in one step.

I'll create a change with artifacts:
- proposal.md (what & why)
- design.md (how)
- tasks.md (implementation steps)

When ready to implement, run /opsx:apply

---

**Input**: The argument after \`/opsx:propose\` is the change name (kebab-case), OR a description of what the user wants to build.

**Steps**

1. **If no input provided, ask what they want to build**

   Use the **AskUserQuestion tool** (open-ended, no preset options) to ask:
   > "What change do you want to work on? Describe what you want to build or fix."

   From their description, derive a kebab-case name (e.g., "add user authentication" → \`add-user-auth\`).

   **IMPORTANT**: Do NOT proceed without understanding what the user wants to build.

2. **Create the change directory**
   \`\`\`bash
   openspec new change "<name>"
   \`\`\`
   This creates a scaffolded change in the planning home resolved by the CLI with \`.openspec.yaml\`.

3. **Drive the artifact loop with \`next-artifact\`**

   Use the **TodoWrite tool** to track progress.

   Repeat until \`{ "done": true }\`:
   \`\`\`bash
   openspec agent next-artifact --change "<name>"
   \`\`\`

   Each non-done response returns the JSON instructions payload for exactly one ready artifact:
   - \`artifactId\`, \`resolvedOutputPath\`: which file to write and where
   - \`template\`: the structure to use for your output (fill in its sections)
   - \`instruction\`: schema-specific guidance for this artifact type
   - \`context\`, \`rules\`: constraints for YOU — do NOT copy these into the file
   - \`dependencies\`: completed artifacts to read for context before writing

   For each response:
   1. Read any \`dependencies\` files for context
   2. Write the artifact file (use \`template\` as the structure, write to \`resolvedOutputPath\`)
   3. Show brief progress: "Created <artifact-id>"
   4. Re-invoke \`openspec agent next-artifact --change "<name>"\` and continue

   If an artifact requires user input (context unclear), use the **AskUserQuestion tool** to clarify, then continue.

4. **Show final status**
   \`\`\`bash
   openspec status --change "<name>"
   \`\`\`

**Output**

After completing all artifacts, summarize:
- Change name and location
- List of artifacts created with brief descriptions
- What's ready: "All artifacts created! Ready for implementation."
- Prompt: "Run \`/opsx:apply\` to start implementing."

**Artifact Creation Guidelines**

- Follow the \`instruction\` field from \`openspec instructions\` for each artifact type
- The schema defines what each artifact should contain - follow it
- Read dependency artifacts for context before creating new ones
- Use \`template\` as the structure for your output file - fill in its sections
- **IMPORTANT**: \`context\` and \`rules\` are constraints for YOU, not content for the file
  - Do NOT copy \`<context>\`, \`<rules>\`, \`<project_context>\` blocks into the artifact
  - These guide what you write, but should never appear in the output

**Guardrails**
- Create ALL artifacts needed for implementation (as defined by schema's \`apply.requires\`)
- Always read dependency artifacts before creating a new one
- If context is critically unclear, ask the user - but prefer making reasonable decisions to keep momentum
- If a change with that name already exists, ask if user wants to continue it or create a new one
- Verify each artifact file exists after writing before proceeding to next`
  };
}
