/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

const refineInstructions = `Review and refine change artifacts for cross-artifact consistency, best-practice alignment, and implementation readiness. Tracks issues in a scratchpad file scoped to the change.

**Input**: Optionally specify a change name (e.g., \`/opsx:refine add-auth\`).

**Steps**

1. **If no change name provided, prompt for selection**

   Run \`openspec list --json\` to get available changes. Use the **AskUserQuestion tool** to let the user select.

   Show only active changes (not already archived).
   Include the schema used for each change if available.

   **IMPORTANT**: Do NOT guess or auto-select a change. Always let the user choose.

2. **Load change artifacts**
   \`\`\`bash
   openspec status --change "<name>" --json
   \`\`\`
   Read all existing artifacts (proposal.md, design.md, tasks.md, specs/) from the change directory.

3. **Create the scratchpad**

   Create \`openspec/changes/<change-name>/scratchpad.md\` using the format in [Scratchpad Format](#scratchpad-format).

   **IMPORTANT**: The scratchpad MUST be used to track issues and working decisions throughout the refine process.

4. **Cross-artifact consistency checks**

   Compare artifacts against each other for contradictions, gaps, and ambiguities:

   - **Proposal → Specs**: Does every goal in the proposal have corresponding requirements in specs?
   - **Specs → Design**: Does the design address all requirements and scenarios?
   - **Design → Tasks**: Do tasks cover all design decisions? Are implementation steps aligned?
   - **Specs → Tasks**: Are all requirements traceable to at least one task?

   Record each issue found in the scratchpad with priority:
   - **P0**: Contradiction between artifacts (e.g., spec says X, design says Y)
   - **P1**: Gap in coverage (e.g., requirement with no corresponding task)
   - **P2**: Ambiguity or unclear intent (e.g., vague acceptance criteria)

5. **Best-practice validation**

   Check artifacts against common quality standards:

   - Tasks have clear acceptance criteria
   - Specs define measurable scenarios (Given/When/Then or equivalent)
   - Design decisions include rationale
   - No circular or missing dependencies in task ordering
   - Edge cases and error states are addressed

   Add findings to the scratchpad.

6. **Address issues one at a time**

   For each issue in priority order (P0 first):
   - Present the issue to the user with context
   - Propose a fix (artifact update)
   - Apply the fix after user approval
   - Update the scratchpad status to reflect the artifact state
   - **Commit the scratchpad and updated artifacts together** (if the user approves)

   **IMPORTANT**: Address one issue at a time so the user can review each change.

7. **Final status**

   When all issues are resolved (or the user decides to stop):
   \`\`\`bash
   openspec status --change "<name>"
   \`\`\`

   Show summary: how many issues were found, resolved, and remaining.
   If issues remain, note them as open in the scratchpad for future sessions.

**Scratchpad Rules**

- Issue status MUST reflect the state of the openspec artifacts (not implementation status)
- Keep "Last updated" date current
- List issues in priority order: P0, P1, P2
- Use format \`P<L>(i)\` where L is level and i is index (e.g., P0(1), P1(2))
- The scratchpad is scoped per-change and persists across refine sessions
- Commit the scratchpad with artifact updates to preserve convergence history

**Scratchpad Format**

\`\`\`markdown
## <change-name> Refinement Scratchpad

Tracks openspec-refine issues and working decisions for the \\\`<change-name>\\\` change.
This is a working document, not a spec artifact.

Last updated: YYYY-MM-DD

### Status Legend
- **Open**: Not yet captured consistently in OpenSpec artifacts
- **Needs refinement**: Partially captured; artifacts still need work
- **Consistent**: Artifacts are aligned with current intended behavior

### Key References
- (List any external references used to resolve issues)

### Current Working Constraints / Decisions
- (List constraints or decisions affecting the current issue)

### Issue List

#### P0(1): <title>
- **Status**: <status>
- **Notes**: <clarify the status>
- **Artifacts touched**:
  - \\\`openspec/changes/<change-name>/...\\\`

#### P1(1): <title>
...

### Open Questions
- (Questions needing user clarification)
\`\`\`

**Graceful Degradation**

- If only proposal.md exists: check for completeness and clarity, skip cross-artifact checks
- If proposal + specs exist: check proposal-spec consistency, skip design/task checks
- If full artifacts: run all checks
- Always note which checks were skipped and why`;

export function getRefineChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-refine-change',
    description: 'Refine change artifacts for cross-artifact consistency, best-practice alignment, and implementation readiness. Use when the user wants to review artifact quality before implementation.',
    instructions: refineInstructions,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxRefineCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Refine',
    description: 'Refine change artifacts for consistency and quality before implementation',
    category: 'Workflow',
    tags: ['workflow', 'refine', 'quality'],
    content: refineInstructions.replace(
      'Optionally specify a change name (e.g., `/opsx:refine add-auth`).',
      'The argument after `/opsx:refine` is the change name (e.g., `/opsx:refine add-auth`).',
    ),
  };
}
