/**
 * Shared store-selection guidance for skill template workflows.
 *
 * Interpolated into every workflow's instructions so generated skills
 * consistently teach how to target a registered store with `--store <id>`.
 */
export const STORE_SELECTION_GUIDANCE = `**Store selection:** If the user names a store (a store is a standalone OpenSpec repo registered on this machine) or the work lives in one, run \`openspec store list --json\` to discover registered store ids, then pass \`--store <id>\` on the commands that read or write specs and changes (\`new change\`, \`status\`, \`instructions\`, \`list\`, \`show\`, \`validate\`, \`archive\`, \`doctor\`, \`context\`, \`schemas\`, \`view\`). Once selected, treat \`--store <id>\` as sticky for the rest of the workflow. Every unscoped example of those commands below is shorthand: before running it, append the flag. For example, run \`openspec status --change "<name>" --json --store "<id>"\`, not the unscoped form shown below. Other commands do not take the flag. Hints printed by commands already carry the flag; keep it on follow-ups. Without a store, commands act on the nearest local \`openspec/\` root.

**Change directories:** New changes start in \`proposed/\`. When the user approves a finished plan in conversation or invokes apply for it, move its resolved \`changeRoot\` to \`<planningHome.changesDir>/approved/<name>\` before implementation, creating the parent if needed. Leave incomplete plans in place and report missing artifacts. Use your filesystem tools, preserve contents, and never overwrite another change. Stop if the move fails. If already approved, leave it there; after a move, refresh status and instructions for current paths. Approval alone does not request implementation. Archive approved changes, never proposed ones; completed flat changes retain their existing archive workflow. Existing flat changes remain usable; leave them in place until approved or applied.`;
