/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';
import { STORE_SELECTION_GUIDANCE } from './store-selection.js';

export const VERIFY_DIMENSIONS_REFERENCE_FILE = 'references/verification-dimensions.md';
export const VERIFY_DIMENSIONS_REFERENCE = `# Verification dimensions

Verification audits a change across three dimensions. Each dimension can raise CRITICAL, WARNING, or SUGGESTION issues.

## Completeness

**Task Completion**:
- If \`contextFiles.tasks\` exists, read every file path in it
- Parse checkboxes: \`- [ ]\` (incomplete) vs \`- [x]\` (complete)
- Count complete vs total tasks
- If incomplete tasks exist:
  - Add CRITICAL issue for each incomplete task
  - Recommendation: "Complete task: <description>" or "Mark as done if already implemented"

**Spec Coverage**:
- If delta specs exist in \`contextFiles.specs\`:
  - Extract all requirements (marked with "### Requirement:")
  - For each requirement:
    - Search codebase for keywords related to the requirement
    - Assess if implementation likely exists
  - If requirements appear unimplemented:
    - Add CRITICAL issue: "Requirement not found: <requirement name>"
    - Recommendation: "Implement requirement X: <description>"

## Correctness

**Requirement Implementation Mapping**:
- For each requirement from delta specs:
  - Search codebase for implementation evidence
  - If found, note file paths and line ranges
  - Assess if implementation matches requirement intent
  - If divergence detected:
    - Add WARNING: "Implementation may diverge from spec: <details>"
    - Recommendation: "Review <file>:<lines> against requirement X"

**Scenario Coverage**:
- For each scenario in delta specs (marked with "#### Scenario:"):
  - Check if conditions are handled in code
  - Check if tests exist covering the scenario
  - If scenario appears uncovered:
    - Add WARNING: "Scenario not covered: <scenario name>"
    - Recommendation: "Add test or implementation for scenario: <description>"

## Coherence

**Design Adherence**:
- If \`contextFiles.design\` exists:
  - Extract key decisions (look for sections like "Decision:", "Approach:", "Architecture:")
  - Verify implementation follows those decisions
  - If contradiction detected:
    - Add WARNING: "Design decision not followed: <decision>"
    - Recommendation: "Update implementation or revise design.md to match reality"
- If no design.md: Skip design adherence check, note "No design.md to verify against"

**Code Pattern Consistency**:
- Review new code for consistency with project patterns
- Check file naming, directory structure, coding style
- If significant deviations found:
  - Add SUGGESTION: "Code pattern deviation: <details>"
  - Recommendation: "Consider following project pattern: <example>"

## Severity levels

1. **CRITICAL** (Must fix before archive):
   - Incomplete tasks
   - Missing requirement implementations
   - Each with specific, actionable recommendation

2. **WARNING** (Should fix):
   - Spec/design divergences
   - Missing scenario coverage
   - Each with specific recommendation

3. **SUGGESTION** (Nice to fix):
   - Pattern inconsistencies
   - Minor improvements
   - Each with specific recommendation

## Verification heuristics

- **Completeness**: Focus on objective checklist items (checkboxes, requirements list)
- **Correctness**: Use keyword search, file path analysis, reasonable inference - don't require perfect certainty
- **Coherence**: Look for glaring inconsistencies, don't nitpick style
- **False Positives**: When uncertain, prefer SUGGESTION over WARNING, WARNING over CRITICAL
- **Actionability**: Every issue must have a specific recommendation with file/line references where applicable

## Graceful degradation

- If only tasks.md exists: verify task completion only, skip spec/design checks
- If tasks + specs exist: verify completeness and correctness, skip design
- If full artifacts: verify all three dimensions
- Always note which checks were skipped and why
`;

export function getVerifyChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'openspec-verify-change',
    description: 'Audit a change for completeness/correctness/coherence and produce a CRITICAL/WARNING/SUGGESTION scorecard. Use when validating that implementation matches artifacts before archiving — this only inspects and reports; use openspec-apply-change to do the implementation work, and openspec-archive-change to finalize once verification passes.',
    instructions: `Verify that an implementation matches the change artifacts (specs, tasks, design).

${STORE_SELECTION_GUIDANCE}

**Use when:** you need a read-only completeness/correctness/coherence audit of a change before archiving. This skill only inspects and reports — use \`openspec-apply-change\` to implement or fix the work it flags, and \`openspec-archive-change\` to finalize once the scorecard is clean.

**Inputs:** optionally a change name. If omitted, infer it from conversation context; if vague or ambiguous, run \`openspec list --json\` and prompt for a selection (never auto-select).

**Input**: Optionally specify a change name. If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **If no change name provided, prompt for selection**

   Run \`openspec list --json\` to get available changes. Use the **AskUserQuestion tool** to let the user select.

   Show changes that have implementation tasks (tasks artifact exists).
   Include the schema used for each change if available.
   Mark changes with incomplete tasks as "(In Progress)".

   **IMPORTANT**: Do NOT guess or auto-select a change. Always let the user choose.

2. **Check status to understand the schema**
   \`\`\`bash
   openspec status --change "<name>" --json
   \`\`\`
   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used (e.g., "spec-driven")
   - \`planningHome\`, \`changeRoot\`, \`artifactPaths\`, and \`actionContext\`: path and scope context
   - Which artifacts exist for this change

3. **Get planning context and load artifacts**

   \`\`\`bash
   openspec instructions apply --change "<name>" --json
   \`\`\`

   This returns the change directory and \`contextFiles\` (artifact ID -> array of concrete file paths). Read all available artifacts from \`contextFiles\`.

4. **Initialize verification report structure**

   Create a report structure with three dimensions:
   - **Completeness**: Track tasks and spec coverage
   - **Correctness**: Track requirement implementation and scenario coverage
   - **Coherence**: Track design adherence and pattern consistency

   Each dimension can have CRITICAL, WARNING, or SUGGESTION issues.

5. **Verify each dimension**

   Audit the change across all three dimensions using the artifacts loaded in step 3:
   - **Completeness**: count \`contextFiles.tasks\` checkboxes (complete vs incomplete) and check each \`### Requirement:\` from delta specs for implementation evidence.
   - **Correctness**: map each requirement and each \`#### Scenario:\` to implementation/test evidence with \`file.ts:line\` references, flagging divergences.
   - **Coherence**: verify the implementation follows any \`contextFiles.design\` decisions and stays consistent with project patterns.

   Record issues at the appropriate severity (CRITICAL / WARNING / SUGGESTION), each with a specific, actionable recommendation. Degrade gracefully when artifacts are missing (e.g. tasks-only), and note which checks were skipped and why.

   See \`references/verification-dimensions.md\` for the full checklist of the three dimensions (completeness, correctness, coherence) and severity levels.

6. **Generate Verification Report**

   **Summary Scorecard**:
   \`\`\`
   ## Verification Report: <change-name>

   ### Summary
   | Dimension    | Status           |
   |--------------|------------------|
   | Completeness | X/Y tasks, N reqs|
   | Correctness  | M/N reqs covered |
   | Coherence    | Followed/Issues  |
   \`\`\`

   **Issues by Priority**:

   1. **CRITICAL** (Must fix before archive):
      - Incomplete tasks
      - Missing requirement implementations
      - Each with specific, actionable recommendation

   2. **WARNING** (Should fix):
      - Spec/design divergences
      - Missing scenario coverage
      - Each with specific recommendation

   3. **SUGGESTION** (Nice to fix):
      - Pattern inconsistencies
      - Minor improvements
      - Each with specific recommendation

   **Final Assessment**:
   - If CRITICAL issues: "X critical issue(s) found. Fix before archiving."
   - If only warnings: "No critical issues. Y warning(s) to consider. Ready for archive (with noted improvements)."
   - If all clear: "All checks passed. Ready for archive."

**Output Format**

Use clear markdown with:
- Table for summary scorecard
- Grouped lists for issues (CRITICAL/WARNING/SUGGESTION)
- Code references in format: \`file.ts:123\`
- Specific, actionable recommendations
- No vague suggestions like "consider reviewing"

**Success:** the verification report is produced and every check is accounted for — each task in \`contextFiles.tasks\` is counted as complete or flagged CRITICAL, each \`### Requirement:\` from the delta specs is mapped to pass/fail implementation evidence (with \`file.ts:line\` references), each \`#### Scenario:\` is marked covered or flagged, and any skipped dimension is noted with its reason. The scorecard table renders with a Completeness/Correctness/Coherence row each and ends in a final assessment (all clear, warnings-only, or CRITICAL count).

**Failure & recovery**
- **No change name and none inferable:** run \`openspec list --json\` and use the AskUserQuestion tool to have the user pick — do not guess or auto-select.
- **\`openspec status\` / \`openspec instructions apply\` errors or the change is not found:** re-check the name against \`openspec list --json\`; if the change was never scaffolded, hand off to \`openspec-new-change\` or \`openspec-propose\`.
- **Incomplete tasks or unimplemented requirements (CRITICAL):** stop short of archiving and route the work to \`openspec-apply-change\` to finish it, then re-run this verification.
- **Only partial artifacts exist (tasks but no specs/design):** degrade gracefully — verify the dimensions you can, and explicitly note in the report which checks were skipped and why.

**Related:** \`openspec-archive-change\` to finalize once verification passes; \`openspec-apply-change\` to implement or fix anything flagged CRITICAL.`,
    license: 'MIT',
    compatibility: 'Requires openspec CLI.',
    metadata: { author: 'openspec', version: '1.0' },
  };
}

export function getOpsxVerifyCommandTemplate(): CommandTemplate {
  return {
    name: 'OPSX: Verify',
    description: 'Verify implementation matches change artifacts before archiving',
    category: 'Workflow',
    tags: ['workflow', 'verify', 'experimental'],
    content: `Verify that an implementation matches the change artifacts (specs, tasks, design).

${STORE_SELECTION_GUIDANCE}

**Input**: Optionally specify a change name after \`/opsx:verify\` (e.g., \`/opsx:verify add-auth\`). If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **If no change name provided, prompt for selection**

   Run \`openspec list --json\` to get available changes. Use the **AskUserQuestion tool** to let the user select.

   Show changes that have implementation tasks (tasks artifact exists).
   Include the schema used for each change if available.
   Mark changes with incomplete tasks as "(In Progress)".

   **IMPORTANT**: Do NOT guess or auto-select a change. Always let the user choose.

2. **Check status to understand the schema**
   \`\`\`bash
   openspec status --change "<name>" --json
   \`\`\`
   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used (e.g., "spec-driven")
   - \`planningHome\`, \`changeRoot\`, \`artifactPaths\`, and \`actionContext\`: path and scope context
   - Which artifacts exist for this change

3. **Get planning context and load artifacts**

   \`\`\`bash
   openspec instructions apply --change "<name>" --json
   \`\`\`

   This returns the change directory and \`contextFiles\` (artifact ID -> array of concrete file paths). Read all available artifacts from \`contextFiles\`.

4. **Initialize verification report structure**

   Create a report structure with three dimensions:
   - **Completeness**: Track tasks and spec coverage
   - **Correctness**: Track requirement implementation and scenario coverage
   - **Coherence**: Track design adherence and pattern consistency

   Each dimension can have CRITICAL, WARNING, or SUGGESTION issues.

5. **Verify Completeness**

   **Task Completion**:
   - If \`contextFiles.tasks\` exists, read every file path in it
   - Parse checkboxes: \`- [ ]\` (incomplete) vs \`- [x]\` (complete)
   - Count complete vs total tasks
   - If incomplete tasks exist:
     - Add CRITICAL issue for each incomplete task
     - Recommendation: "Complete task: <description>" or "Mark as done if already implemented"

   **Spec Coverage**:
   - If delta specs exist in \`contextFiles.specs\`:
     - Extract all requirements (marked with "### Requirement:")
     - For each requirement:
       - Search codebase for keywords related to the requirement
       - Assess if implementation likely exists
     - If requirements appear unimplemented:
       - Add CRITICAL issue: "Requirement not found: <requirement name>"
       - Recommendation: "Implement requirement X: <description>"

6. **Verify Correctness**

   **Requirement Implementation Mapping**:
   - For each requirement from delta specs:
     - Search codebase for implementation evidence
     - If found, note file paths and line ranges
     - Assess if implementation matches requirement intent
     - If divergence detected:
       - Add WARNING: "Implementation may diverge from spec: <details>"
       - Recommendation: "Review <file>:<lines> against requirement X"

   **Scenario Coverage**:
   - For each scenario in delta specs (marked with "#### Scenario:"):
     - Check if conditions are handled in code
     - Check if tests exist covering the scenario
     - If scenario appears uncovered:
       - Add WARNING: "Scenario not covered: <scenario name>"
       - Recommendation: "Add test or implementation for scenario: <description>"

7. **Verify Coherence**

   **Design Adherence**:
   - If \`contextFiles.design\` exists:
     - Extract key decisions (look for sections like "Decision:", "Approach:", "Architecture:")
     - Verify implementation follows those decisions
     - If contradiction detected:
       - Add WARNING: "Design decision not followed: <decision>"
       - Recommendation: "Update implementation or revise design.md to match reality"
   - If no design.md: Skip design adherence check, note "No design.md to verify against"

   **Code Pattern Consistency**:
   - Review new code for consistency with project patterns
   - Check file naming, directory structure, coding style
   - If significant deviations found:
     - Add SUGGESTION: "Code pattern deviation: <details>"
     - Recommendation: "Consider following project pattern: <example>"

8. **Generate Verification Report**

   **Summary Scorecard**:
   \`\`\`
   ## Verification Report: <change-name>

   ### Summary
   | Dimension    | Status           |
   |--------------|------------------|
   | Completeness | X/Y tasks, N reqs|
   | Correctness  | M/N reqs covered |
   | Coherence    | Followed/Issues  |
   \`\`\`

   **Issues by Priority**:

   1. **CRITICAL** (Must fix before archive):
      - Incomplete tasks
      - Missing requirement implementations
      - Each with specific, actionable recommendation

   2. **WARNING** (Should fix):
      - Spec/design divergences
      - Missing scenario coverage
      - Each with specific recommendation

   3. **SUGGESTION** (Nice to fix):
      - Pattern inconsistencies
      - Minor improvements
      - Each with specific recommendation

   **Final Assessment**:
   - If CRITICAL issues: "X critical issue(s) found. Fix before archiving."
   - If only warnings: "No critical issues. Y warning(s) to consider. Ready for archive (with noted improvements)."
   - If all clear: "All checks passed. Ready for archive."

**Verification Heuristics**

- **Completeness**: Focus on objective checklist items (checkboxes, requirements list)
- **Correctness**: Use keyword search, file path analysis, reasonable inference - don't require perfect certainty
- **Coherence**: Look for glaring inconsistencies, don't nitpick style
- **False Positives**: When uncertain, prefer SUGGESTION over WARNING, WARNING over CRITICAL
- **Actionability**: Every issue must have a specific recommendation with file/line references where applicable

**Graceful Degradation**

- If only tasks.md exists: verify task completion only, skip spec/design checks
- If tasks + specs exist: verify completeness and correctness, skip design
- If full artifacts: verify all three dimensions
- Always note which checks were skipped and why

**Output Format**

Use clear markdown with:
- Table for summary scorecard
- Grouped lists for issues (CRITICAL/WARNING/SUGGESTION)
- Code references in format: \`file.ts:123\`
- Specific, actionable recommendations
- No vague suggestions like "consider reviewing"`
  };
}
