import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import os from 'os';
import path from 'path';
import { promises as fs } from 'fs';
import {
  includesGitHubCopilot,
  generateCopilotSetupSteps,
  generateCopilotAgentFile,
  COPILOT_CLOUD_FILES,
  removeCopilotCloudFiles,
  writeCopilotCloudFiles,
} from '../../src/core/github-copilot/cloud-agent.js';

describe('GitHub Copilot Cloud Agent', () => {
  let tempDir: string;

  function removeManagedMarker(content: string): string {
    return content
      .replace(/^# Generated by OpenSpec for GitHub Copilot coding agent support\.\n\n/, '')
      .replace(/\n<!-- Generated by OpenSpec for GitHub Copilot coding agent support\. -->\n/, '');
  }

  function generateLegacyCopilotAgentFile(): string {
    return removeManagedMarker(generateCopilotAgentFile())
      .replace(
        `tools:
  - "execute"
  - "read"
  - "search"
  - "edit"`,
        `tools:
  - "terminal"`
      )
      .replace(
        'You are a specialized agent for managing OpenSpec workflows. You have access to the `openspec` CLI through shell commands, pre-installed in the development environment via `copilot-setup-steps.yml`.',
        'You are a specialized agent for managing OpenSpec workflows. You have access to the `openspec` CLI which is pre-installed in the development environment via `copilot-setup-steps.yml`.'
      )
      .replace(
        '| `openspec status [--change <name>] [--json]` | Show artifact progress for a change |',
        '| `openspec status [--json]` | Show artifact progress for active changes |'
      )
      .replace(
        '| `openspec instructions [artifact] [--change <name>] [--json]` | Get next-step instructions for a change |',
        '| `openspec instructions [--json]` | Get next-step instructions for a change |'
      );
  }

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'openspec-copilot-cloud-agent-'));
  });

  afterEach(async () => {
    await fs.rm(tempDir, { recursive: true, force: true });
  });

  describe('includesGitHubCopilot', () => {
    it('returns true when github-copilot is in the list', () => {
      expect(includesGitHubCopilot(['claude', 'github-copilot', 'cursor'])).toBe(true);
    });

    it('returns false when github-copilot is not in the list', () => {
      expect(includesGitHubCopilot(['claude', 'cursor'])).toBe(false);
    });

    it('returns false for empty list', () => {
      expect(includesGitHubCopilot([])).toBe(false);
    });
  });

  describe('generateCopilotSetupSteps', () => {
    it('generates valid YAML workflow content', () => {
      const content = generateCopilotSetupSteps();
      expect(content).toContain('Generated by OpenSpec for GitHub Copilot coding agent support.');
      expect(content).toContain('name: "Copilot Setup Steps"');
      expect(content).toContain('copilot-setup-steps:');
      expect(content).toContain('runs-on: ubuntu-latest');
      expect(content).toContain('npm install -g @fission-ai/openspec');
      expect(content).toContain('openspec --version');
    });
  });

  describe('generateCopilotAgentFile', () => {
    it('generates agent markdown with frontmatter', () => {
      const content = generateCopilotAgentFile();
      expect(content).toMatch(/^---\n/);
      expect(content).toContain('Generated by OpenSpec for GitHub Copilot coding agent support.');
      expect(content).toContain('name: OpenSpec');
      expect(content).toContain('description:');
      expect(content).toContain('tools:');
      expect(content).toContain('execute');
      expect(content).toContain('read');
      expect(content).toContain('search');
      expect(content).toContain('edit');
      expect(content).toContain('# OpenSpec Agent');
      expect(content).toContain('openspec list');
      expect(content).toContain('openspec validate');
    });
  });

  describe('COPILOT_CLOUD_FILES', () => {
    it('has correct file paths', () => {
      expect(COPILOT_CLOUD_FILES.setupSteps).toBe(path.join('.github', 'workflows', 'copilot-setup-steps.yml'));
      expect(COPILOT_CLOUD_FILES.agent).toBe(path.join('.github', 'agents', 'openspec.agent.md'));
    });
  });

  describe('writeCopilotCloudFiles', () => {
    it('writes missing cloud files and creates parent directories', async () => {
      const result = await writeCopilotCloudFiles(tempDir);

      expect(result).toEqual({ setupStepsWritten: true, agentWritten: true });
      await expect(fs.stat(path.join(tempDir, COPILOT_CLOUD_FILES.setupSteps))).resolves.toBeTruthy();
      await expect(fs.stat(path.join(tempDir, COPILOT_CLOUD_FILES.agent))).resolves.toBeTruthy();
    });

    it('skips existing files by default', async () => {
      const setupStepsPath = path.join(tempDir, COPILOT_CLOUD_FILES.setupSteps);
      const agentPath = path.join(tempDir, COPILOT_CLOUD_FILES.agent);
      await fs.mkdir(path.dirname(setupStepsPath), { recursive: true });
      await fs.mkdir(path.dirname(agentPath), { recursive: true });
      await fs.writeFile(setupStepsPath, 'custom setup');
      await fs.writeFile(agentPath, 'custom agent');

      const result = await writeCopilotCloudFiles(tempDir);

      expect(result).toEqual({ setupStepsWritten: false, agentWritten: false });
      await expect(fs.readFile(setupStepsPath, 'utf8')).resolves.toBe('custom setup');
      await expect(fs.readFile(agentPath, 'utf8')).resolves.toBe('custom agent');
    });

    it('overwrites existing files when force is true', async () => {
      const setupStepsPath = path.join(tempDir, COPILOT_CLOUD_FILES.setupSteps);
      const agentPath = path.join(tempDir, COPILOT_CLOUD_FILES.agent);
      await fs.mkdir(path.dirname(setupStepsPath), { recursive: true });
      await fs.mkdir(path.dirname(agentPath), { recursive: true });
      await fs.writeFile(setupStepsPath, 'custom setup');
      await fs.writeFile(agentPath, 'custom agent');

      const result = await writeCopilotCloudFiles(tempDir, { force: true });

      expect(result).toEqual({ setupStepsWritten: true, agentWritten: true });
      await expect(fs.readFile(setupStepsPath, 'utf8')).resolves.toContain('copilot-setup-steps:');
      await expect(fs.readFile(agentPath, 'utf8')).resolves.toContain('# OpenSpec Agent');
    });
  });

  describe('removeCopilotCloudFiles', () => {
    it('removes only existing cloud files and returns the removal count', async () => {
      const setupStepsPath = path.join(tempDir, COPILOT_CLOUD_FILES.setupSteps);
      const agentPath = path.join(tempDir, COPILOT_CLOUD_FILES.agent);
      await writeCopilotCloudFiles(tempDir);
      await fs.rm(agentPath, { force: true });

      const removed = await removeCopilotCloudFiles(tempDir);

      expect(removed).toBe(1);
      await expect(fs.stat(setupStepsPath)).rejects.toMatchObject({ code: 'ENOENT' });
      await expect(fs.stat(agentPath)).rejects.toMatchObject({ code: 'ENOENT' });
    });

    it('keeps customized cloud files', async () => {
      const setupStepsPath = path.join(tempDir, COPILOT_CLOUD_FILES.setupSteps);
      const agentPath = path.join(tempDir, COPILOT_CLOUD_FILES.agent);
      await fs.mkdir(path.dirname(setupStepsPath), { recursive: true });
      await fs.mkdir(path.dirname(agentPath), { recursive: true });
      await fs.writeFile(setupStepsPath, 'custom setup');
      await fs.writeFile(agentPath, 'custom agent');

      const removed = await removeCopilotCloudFiles(tempDir);

      expect(removed).toBe(0);
      await expect(fs.readFile(setupStepsPath, 'utf8')).resolves.toBe('custom setup');
      await expect(fs.readFile(agentPath, 'utf8')).resolves.toBe('custom agent');
    });

    it('keeps modified marker-bearing cloud files', async () => {
      const setupStepsPath = path.join(tempDir, COPILOT_CLOUD_FILES.setupSteps);
      const agentPath = path.join(tempDir, COPILOT_CLOUD_FILES.agent);
      await fs.mkdir(path.dirname(setupStepsPath), { recursive: true });
      await fs.mkdir(path.dirname(agentPath), { recursive: true });
      await fs.writeFile(setupStepsPath, `${generateCopilotSetupSteps()}\n# custom change\n`);
      await fs.writeFile(agentPath, `${generateCopilotAgentFile()}\ncustom change\n`);

      const removed = await removeCopilotCloudFiles(tempDir);

      expect(removed).toBe(0);
      await expect(fs.readFile(setupStepsPath, 'utf8')).resolves.toContain('custom change');
      await expect(fs.readFile(agentPath, 'utf8')).resolves.toContain('custom change');
    });

    it('removes markerless current generated cloud files', async () => {
      const setupStepsPath = path.join(tempDir, COPILOT_CLOUD_FILES.setupSteps);
      const agentPath = path.join(tempDir, COPILOT_CLOUD_FILES.agent);
      await fs.mkdir(path.dirname(setupStepsPath), { recursive: true });
      await fs.mkdir(path.dirname(agentPath), { recursive: true });
      await fs.writeFile(setupStepsPath, removeManagedMarker(generateCopilotSetupSteps()));
      await fs.writeFile(agentPath, removeManagedMarker(generateCopilotAgentFile()));

      const removed = await removeCopilotCloudFiles(tempDir);

      expect(removed).toBe(2);
      await expect(fs.stat(setupStepsPath)).rejects.toMatchObject({ code: 'ENOENT' });
      await expect(fs.stat(agentPath)).rejects.toMatchObject({ code: 'ENOENT' });
    });

    it('removes markerless legacy generated cloud files', async () => {
      const setupStepsPath = path.join(tempDir, COPILOT_CLOUD_FILES.setupSteps);
      const agentPath = path.join(tempDir, COPILOT_CLOUD_FILES.agent);
      await fs.mkdir(path.dirname(setupStepsPath), { recursive: true });
      await fs.mkdir(path.dirname(agentPath), { recursive: true });
      await fs.writeFile(setupStepsPath, removeManagedMarker(generateCopilotSetupSteps()));
      await fs.writeFile(agentPath, generateLegacyCopilotAgentFile());

      const removed = await removeCopilotCloudFiles(tempDir);

      expect(removed).toBe(2);
      await expect(fs.stat(setupStepsPath)).rejects.toMatchObject({ code: 'ENOENT' });
      await expect(fs.stat(agentPath)).rejects.toMatchObject({ code: 'ENOENT' });
    });
  });
});
