import { describe, expect, it } from 'vitest';

import {
  getSkillTemplates,
  getCommandContents,
  generateSkillContent,
} from '../../../src/core/shared/skill-generation.js';
import {
  ALL_WORKFLOWS,
  CORE_WORKFLOWS,
  getProfileWorkflows,
} from '../../../src/core/profiles.js';
import { transformToSkillReferences } from '../../../src/utils/command-references.js';

/**
 * The default `core` profile installs six of the twelve workflows. Anything it
 * generates that names one of the other six sends the agent to a skill that was
 * never written — a dead end the agent cannot recover from (#1734, umbrella
 * #919). Assert it on the generated bytes, both spellings: the canonical
 * `/opsx:<id>` a command file carries and the `/openspec-<skill>` a skills-only
 * install carries.
 */
const coreWorkflows = getProfileWorkflows('core');
const uninstalled = ALL_WORKFLOWS.filter((id) => !coreWorkflows.includes(id));

const skillNameFor = (id: string) => transformToSkillReferences(`/opsx:${id}`);

describe('core profile generates no reference to an uninstalled workflow', () => {
  it('resolves to exactly the six core workflows', () => {
    expect([...coreWorkflows].sort()).toEqual([...CORE_WORKFLOWS].sort());
    expect(uninstalled).toContain('continue');
    expect(uninstalled).toContain('new');
  });

  it('holds for every generated skill body', () => {
    for (const { template, dirName } of getSkillTemplates(coreWorkflows)) {
      const content = generateSkillContent(template, 'TEST');
      const skillsOnly = transformToSkillReferences(content);

      for (const id of uninstalled) {
        expect(content, `${dirName} -> /opsx:${id}`).not.toContain(`/opsx:${id}`);
        expect(skillsOnly, `${dirName} -> ${skillNameFor(id)}`).not.toContain(skillNameFor(id));
      }
    }
  });

  it('holds for every generated command body', () => {
    for (const { id: commandId, body } of getCommandContents(coreWorkflows)) {
      for (const id of uninstalled) {
        expect(body, `${commandId} -> /opsx:${id}`).not.toContain(`/opsx:${id}`);
      }
    }
  });

  it('still names the optional workflows when the profile installs them', () => {
    const expanded = getSkillTemplates(ALL_WORKFLOWS);
    const update = expanded.find(({ workflowId }) => workflowId === 'update');

    expect(update?.template.instructions).toContain('/opsx:continue');
    expect(update?.template.instructions).toContain('/opsx:new');
  });
});
