/**
 * OpenSpec → Pastelsdd Migration
 *
 * Detects projects using the old "openspec" structure and migrates them
 * cleanly to Pastelsdd: deletes old skills/commands generated by openspec
 * (opsx-* prefix), renames the .openspec/ folder to pastelsdd/, and
 * migrates any stale config fields.
 *
 * Migration is triggered automatically during `pastelsdd init` when an
 * .openspec/ directory is detected. The user is prompted to confirm before
 * any changes are made.
 */

import path from 'path';
import { promises as fs } from 'fs';
import chalk from 'chalk';
import { AI_TOOLS } from './config.js';
import { CommandAdapterRegistry } from './command-generation/index.js';
import { ALL_WORKFLOWS } from './profiles.js';
import { FileSystemUtils } from '../utils/file-system.js';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Directory name used by the old openspec tool */
const OPENSPEC_DIR = '.openspec';

/** Old skill prefix used by openspec */
const OPENSPEC_SKILL_PREFIX = 'opsx-';

/** Old slash command prefix used by openspec */
const OPENSPEC_COMMAND_PREFIX = 'opsx-';

/** Old slash command namespace inside pastelsdd directories */
const OPENSPEC_COMMAND_DIR = 'openspec';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface OpenspecDetectionResult {
  /** Whether an .openspec/ directory was found */
  hasOpenspecDir: boolean;
  /** Full path to the .openspec/ directory */
  openspecDirPath: string;
  /** Old opsx-* skill files found across all tool dirs */
  legacySkillFiles: string[];
  /** Old opsx-* / openspec command files found across all tool dirs */
  legacyCommandFiles: string[];
  /** Whether any openspec artifacts were found */
  hasOpenspecArtifacts: boolean;
}

export interface OpenspecMigrationResult {
  /** Whether .openspec/ was renamed to pastelsdd/ */
  renamedDir: boolean;
  /** Skill files deleted */
  deletedSkills: string[];
  /** Command files/dirs deleted */
  deletedCommands: string[];
  /** Errors that occurred */
  errors: string[];
}

// ---------------------------------------------------------------------------
// Detection
// ---------------------------------------------------------------------------

/**
 * Detects openspec artifacts in a project.
 */
export async function detectOpenspecArtifacts(
  projectPath: string
): Promise<OpenspecDetectionResult> {
  const openspecDirPath = path.join(projectPath, OPENSPEC_DIR);
  const hasOpenspecDir = await FileSystemUtils.directoryExists(openspecDirPath);

  const legacySkillFiles: string[] = [];
  const legacyCommandFiles: string[] = [];

  // Scan all known tool skill directories for opsx-* skill dirs
  for (const tool of AI_TOOLS) {
    if (!tool.skillsDir) continue;

    const skillsDir = path.join(projectPath, tool.skillsDir, 'skills');
    if (await FileSystemUtils.directoryExists(skillsDir)) {
      try {
        const entries = await fs.readdir(skillsDir);
        for (const entry of entries) {
          if (entry.startsWith(OPENSPEC_SKILL_PREFIX)) {
            legacySkillFiles.push(path.join(tool.skillsDir, 'skills', entry));
          }
        }
      } catch {
        // ignore
      }
    }

    // Scan for old command files (opsx-*.md or openspec/ dir)
    const adapter = CommandAdapterRegistry.get(tool.value);
    if (!adapter) continue;

    // Check for old opsx-prefixed command files using the adapter's base dir
    for (const workflow of ALL_WORKFLOWS) {
      const cmdPath = adapter.getFilePath(workflow);
      const fullPath = path.isAbsolute(cmdPath) ? cmdPath : path.join(projectPath, cmdPath);
      const dir = path.dirname(fullPath);
      const basename = path.basename(fullPath);

      // Check for opsx-prefixed variant in the same directory
      const opsPrefixedName = basename.replace(/^pastel-/, OPENSPEC_COMMAND_PREFIX);
      if (opsPrefixedName !== basename) {
        const opsPrefixedPath = path.join(dir, opsPrefixedName);
        try {
          await fs.access(opsPrefixedPath);
          const rel = path.relative(projectPath, opsPrefixedPath).replace(/\\/g, '/');
          legacyCommandFiles.push(rel);
        } catch {
          // file doesn't exist
        }
      }
    }

    // Check for old openspec/ command directory (claude-style)
    const toolDir = path.join(projectPath, tool.skillsDir);
    const openspecCmdDir = path.join(toolDir, 'commands', OPENSPEC_COMMAND_DIR);
    if (await FileSystemUtils.directoryExists(openspecCmdDir)) {
      const rel = path.relative(projectPath, openspecCmdDir).replace(/\\/g, '/');
      legacyCommandFiles.push(rel + '/');
    }
  }

  const hasOpenspecArtifacts =
    hasOpenspecDir ||
    legacySkillFiles.length > 0 ||
    legacyCommandFiles.length > 0;

  return {
    hasOpenspecDir,
    openspecDirPath,
    legacySkillFiles,
    legacyCommandFiles,
    hasOpenspecArtifacts,
  };
}

// ---------------------------------------------------------------------------
// Summary display
// ---------------------------------------------------------------------------

/**
 * Formats a human-readable summary of what was detected.
 */
export function formatOpenspecDetectionSummary(
  detection: OpenspecDetectionResult
): string {
  const lines: string[] = [];

  lines.push(chalk.bold('OpenSpec project detected'));
  lines.push('');
  lines.push('This project was set up with the old openspec tool.');
  lines.push('Pastelsdd will:');
  lines.push('');

  if (detection.hasOpenspecDir) {
    lines.push(`  • Rename ${chalk.cyan(OPENSPEC_DIR + '/')} → ${chalk.cyan('pastelsdd/')}`);
  }

  if (detection.legacySkillFiles.length > 0) {
    lines.push(
      `  • Delete ${detection.legacySkillFiles.length} old opsx-* skill director${detection.legacySkillFiles.length === 1 ? 'y' : 'ies'}`
    );
    for (const f of detection.legacySkillFiles) {
      lines.push(`      ${chalk.dim(f + '/')}`);
    }
  }

  if (detection.legacyCommandFiles.length > 0) {
    lines.push(
      `  • Delete ${detection.legacyCommandFiles.length} old openspec command file${detection.legacyCommandFiles.length === 1 ? '' : 's'}`
    );
    for (const f of detection.legacyCommandFiles) {
      lines.push(`      ${chalk.dim(f)}`);
    }
  }

  lines.push('');
  lines.push(chalk.dim('Fresh Pastelsdd skills and commands will be installed afterwards.'));

  return lines.join('\n');
}

/**
 * Formats a summary of what was done during migration.
 */
export function formatOpenspecMigrationSummary(
  result: OpenspecMigrationResult
): string {
  const lines: string[] = [];

  if (result.renamedDir) {
    lines.push(`  ✓ Renamed ${OPENSPEC_DIR}/ → pastelsdd/`);
  }

  for (const f of result.deletedSkills) {
    lines.push(`  ✓ Deleted skill: ${f}`);
  }

  for (const f of result.deletedCommands) {
    lines.push(`  ✓ Deleted command: ${f}`);
  }

  for (const e of result.errors) {
    lines.push(`  ⚠ ${e}`);
  }

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Migration
// ---------------------------------------------------------------------------

/**
 * Runs the openspec → pastelsdd migration.
 * - Deletes old opsx-* skill directories
 * - Deletes old openspec command files/directories
 * - Renames .openspec/ → pastelsdd/ (only if pastelsdd/ doesn't already exist)
 */
export async function migrateFromOpenspec(
  projectPath: string,
  detection: OpenspecDetectionResult
): Promise<OpenspecMigrationResult> {
  const result: OpenspecMigrationResult = {
    renamedDir: false,
    deletedSkills: [],
    deletedCommands: [],
    errors: [],
  };

  // 1. Delete old opsx-* skill directories
  for (const relPath of detection.legacySkillFiles) {
    const fullPath = path.join(projectPath, relPath);
    try {
      await fs.rm(fullPath, { recursive: true, force: true });
      result.deletedSkills.push(relPath);
    } catch (err: any) {
      result.errors.push(`Could not delete skill ${relPath}: ${err.message}`);
    }
  }

  // 2. Delete old openspec command files / directories
  for (const relPath of detection.legacyCommandFiles) {
    const fullPath = path.join(projectPath, relPath.replace(/\/$/, ''));
    try {
      const stat = await fs.stat(fullPath).catch(() => null);
      if (stat?.isDirectory()) {
        await fs.rm(fullPath, { recursive: true, force: true });
      } else if (stat) {
        await fs.unlink(fullPath);
      }
      result.deletedCommands.push(relPath);
    } catch (err: any) {
      result.errors.push(`Could not delete command ${relPath}: ${err.message}`);
    }
  }

  // 3. Rename .openspec/ → pastelsdd/ (only if pastelsdd/ doesn't already exist)
  if (detection.hasOpenspecDir) {
    const pastelsddPath = path.join(projectPath, 'pastelsdd');
    const pastelsddExists = await FileSystemUtils.directoryExists(pastelsddPath);

    if (pastelsddExists) {
      // pastelsdd/ already exists — just remove .openspec/
      try {
        await fs.rm(detection.openspecDirPath, { recursive: true, force: true });
        result.errors.push(
          `pastelsdd/ already exists — removed .openspec/ without merging. Review manually if needed.`
        );
      } catch (err: any) {
        result.errors.push(`Could not remove .openspec/: ${err.message}`);
      }
    } else {
      try {
        await fs.rename(detection.openspecDirPath, pastelsddPath);
        result.renamedDir = true;
      } catch (err: any) {
        result.errors.push(`Could not rename .openspec/ → pastelsdd/: ${err.message}`);
      }
    }
  }

  return result;
}
