import fs from 'fs';
import os from 'os';
import path from 'path';
import { createRequire } from 'module';
import chalk from 'chalk';

const require = createRequire(import.meta.url);
const { name: PACKAGE_NAME, version: OPENSPEC_VERSION } = require('../../package.json');

const REGISTRY_URL = `https://registry.npmjs.org/${PACKAGE_NAME}/latest`;
const REQUEST_TIMEOUT_MS = 1500;
const CACHE_TTL_MS = 24 * 60 * 60 * 1000;

function cacheFilePath(): string {
  return path.join(os.tmpdir(), 'openspec-version-check.json');
}

/**
 * The check is opt-out and must never get in the way: no network in CI or
 * tests, and an explicit escape hatch for anyone offline or air-gapped.
 */
function isCheckEnabled(): boolean {
  if (process.env.OPENSPEC_NO_UPDATE_CHECK !== undefined) return false;
  if (process.env.CI === 'true') return false;
  if (process.env.NODE_ENV === 'test') return false;
  return true;
}

/**
 * Compares two semver-ish versions. Returns 1 when a > b, -1 when a < b, 0
 * otherwise. Prereleases sort below their release (1.7.0-beta.1 < 1.7.0).
 */
export function compareVersions(a: string, b: string): number {
  const parse = (version: string) => {
    const [core, prerelease] = version.trim().replace(/^v/, '').split('-', 2);
    const parts = core.split('.').map((n) => Number.parseInt(n, 10));
    return {
      numbers: [parts[0] || 0, parts[1] || 0, parts[2] || 0],
      prerelease: prerelease ?? '',
    };
  };

  const left = parse(a);
  const right = parse(b);

  for (let i = 0; i < 3; i++) {
    if (left.numbers[i] > right.numbers[i]) return 1;
    if (left.numbers[i] < right.numbers[i]) return -1;
  }

  if (left.prerelease === right.prerelease) return 0;
  if (left.prerelease === '') return 1;
  if (right.prerelease === '') return -1;
  return left.prerelease > right.prerelease ? 1 : -1;
}

function readCachedVersion(): string | null {
  try {
    const raw = fs.readFileSync(cacheFilePath(), 'utf-8');
    const cached = JSON.parse(raw) as { version?: unknown; checkedAt?: unknown };
    if (typeof cached.version !== 'string' || typeof cached.checkedAt !== 'number') {
      return null;
    }
    if (Date.now() - cached.checkedAt > CACHE_TTL_MS) return null;
    return cached.version;
  } catch {
    return null;
  }
}

function writeCachedVersion(version: string): void {
  try {
    fs.writeFileSync(
      cacheFilePath(),
      JSON.stringify({ version, checkedAt: Date.now() }),
      'utf-8'
    );
  } catch {
    // Cache is an optimization; losing it is harmless.
  }
}

async function fetchLatestVersion(): Promise<string | null> {
  try {
    const response = await fetch(REGISTRY_URL, {
      signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
      headers: { accept: 'application/vnd.npm.install-v1+json' },
    });
    if (!response.ok) return null;
    const body = (await response.json()) as { version?: unknown };
    return typeof body.version === 'string' ? body.version : null;
  } catch {
    return null;
  }
}

/**
 * Returns the published version when the installed CLI is behind it, otherwise
 * null. Never throws and never blocks for longer than the request timeout.
 */
export async function getAvailableCliUpdate(): Promise<string | null> {
  if (!isCheckEnabled()) return null;

  try {
    const latest = readCachedVersion() ?? (await fetchLatestVersion());
    if (!latest) return null;
    writeCachedVersion(latest);
    return compareVersions(latest, OPENSPEC_VERSION) > 0 ? latest : null;
  } catch {
    return null;
  }
}

/**
 * Prints the upgrade hint. Instruction files are generated by the installed
 * CLI, so "up to date" only ever means "matches this CLI" — without this note
 * a stale global install looks like a successful update.
 */
export function displayCliUpdateNote(latestVersion: string): void {
  console.log();
  console.log(
    chalk.yellow(
      `A newer OpenSpec CLI is available (v${OPENSPEC_VERSION} → v${latestVersion}).`
    )
  );
  console.log(chalk.dim(`  npm install -g ${PACKAGE_NAME}@latest`));
  console.log(chalk.dim('  Then run "openspec update" again to pick up new workflows.'));
}
