import path from 'path';
import { createRequire } from 'module';
import chalk from 'chalk';

const require = createRequire(import.meta.url);
const { name: PACKAGE_NAME, version: OPENSPEC_VERSION } = require('../../package.json');

const REGISTRY_URL = `https://registry.npmjs.org/${PACKAGE_NAME}/latest`;
const REQUEST_TIMEOUT_MS = 1500;

/**
 * Values a CI provider may set. GitHub Actions uses "true", others use "1".
 */
const CI_ENABLED_VALUES = new Set(['true', '1']);

/**
 * The check is opt-out and must never get in the way: no network in CI or
 * tests, and an explicit escape hatch for anyone offline or air-gapped.
 */
function isCheckEnabled(): boolean {
  if (process.env.OPENSPEC_NO_UPDATE_CHECK !== undefined) return false;
  if (CI_ENABLED_VALUES.has((process.env.CI ?? '').toLowerCase())) return false;
  if (process.env.NODE_ENV === 'test') return false;
  return true;
}

/**
 * Compares two prerelease tags per SemVer: dot-separated identifiers compared
 * one by one, numeric identifiers numerically (so beta.10 > beta.2), numeric
 * ranking below alphanumeric, and a longer identifier list winning ties.
 */
function comparePrerelease(a: string, b: string): number {
  if (a === b) return 0;
  if (a === '') return 1;
  if (b === '') return -1;

  const left = a.split('.');
  const right = b.split('.');

  for (let i = 0; i < Math.max(left.length, right.length); i++) {
    const l = left[i];
    const r = right[i];
    if (l === undefined) return -1;
    if (r === undefined) return 1;

    const lNumeric = /^\d+$/.test(l);
    const rNumeric = /^\d+$/.test(r);

    if (lNumeric && rNumeric) {
      const diff = Number.parseInt(l, 10) - Number.parseInt(r, 10);
      if (diff !== 0) return diff > 0 ? 1 : -1;
      continue;
    }
    if (lNumeric !== rNumeric) return lNumeric ? -1 : 1;
    if (l !== r) return l > r ? 1 : -1;
  }

  return 0;
}

/**
 * Compares two semver-ish versions. Returns 1 when a > b, -1 when a < b, 0
 * otherwise. Prereleases sort below their release (1.7.0-beta.1 < 1.7.0).
 */
export function compareVersions(a: string, b: string): number {
  const parse = (version: string) => {
    const withoutBuild = version.trim().replace(/^v/, '').split('+', 1)[0] ?? '';
    const separator = withoutBuild.indexOf('-');
    const core = separator === -1 ? withoutBuild : withoutBuild.slice(0, separator);
    const prerelease = separator === -1 ? '' : withoutBuild.slice(separator + 1);
    const parts = core.split('.').map((n) => Number.parseInt(n, 10));
    return {
      numbers: [parts[0] || 0, parts[1] || 0, parts[2] || 0],
      prerelease,
    };
  };

  const left = parse(a);
  const right = parse(b);

  for (let i = 0; i < 3; i++) {
    if (left.numbers[i] > right.numbers[i]) return 1;
    if (left.numbers[i] < right.numbers[i]) return -1;
  }

  return comparePrerelease(left.prerelease, right.prerelease);
}

async function fetchLatestVersion(): Promise<string | null> {
  try {
    const response = await fetch(REGISTRY_URL, {
      signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
      headers: { accept: 'application/vnd.npm.install-v1+json' },
    });
    if (!response.ok) return null;
    const body = (await response.json()) as { version?: unknown };
    return typeof body.version === 'string' ? body.version : null;
  } catch {
    return null;
  }
}

/**
 * Returns the published version when the installed CLI is behind it, otherwise
 * null. Never throws and never blocks for longer than the request timeout.
 */
export async function getAvailableCliUpdate(): Promise<string | null> {
  if (!isCheckEnabled()) return null;

  try {
    const latest = await fetchLatestVersion();
    if (!latest) return null;
    return compareVersions(latest, OPENSPEC_VERSION) > 0 ? latest : null;
  } catch {
    return null;
  }
}

/**
 * Directory the running CLI was loaded from, or null when it cannot be
 * resolved. Shown in the upgrade hint so anyone who upgraded but still runs an
 * old binary — a stale pnpm/volta/npx shim, or two installs on PATH — can see
 * which copy is actually answering.
 */
export function getInstallDir(): string | null {
  try {
    return path.dirname(require.resolve('../../package.json'));
  } catch {
    return null;
  }
}

export function isProjectLocalInstall(installDir: string | null): boolean {
  if (!installDir) return false;
  const projectModules = path.join(process.cwd(), 'node_modules') + path.sep;
  return installDir.startsWith(projectModules);
}

/**
 * Prints the upgrade hint. Instruction files are generated by the installed
 * CLI, so "up to date" only ever means "matches this CLI" — without this note
 * a stale install looks like a successful update.
 */
export function displayCliUpdateNote(latestVersion: string): void {
  const installDir = getInstallDir();

  console.log();
  console.log(
    chalk.yellow(
      `A newer OpenSpec CLI is available (v${OPENSPEC_VERSION} → v${latestVersion}).`
    )
  );
  if (isProjectLocalInstall(installDir)) {
    console.log(chalk.dim(`  Update the ${PACKAGE_NAME} dependency in this project.`));
  } else {
    console.log(chalk.dim(`  npm install -g ${PACKAGE_NAME}@latest`));
  }
  console.log(chalk.dim('  Then run "openspec update" again to pick up new workflows.'));
  if (installDir) {
    console.log(chalk.dim(`  Running from: ${installDir}`));
  }
}
