import { describe, it, expect } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { parseSchema, SchemaValidationError } from '../../../src/core/artifact-graph/schema.js';
import { cliProjectRoot } from '../../helpers/run-cli.js';

/**
 * `parseSchema` checked `artifacts[].requires` but never the `apply` block, so
 * a typo there passed `openspec schema validate` and failed silently at run
 * time: an unknown `apply.requires` id was skipped, turning off the apply gate,
 * and an unmatched `apply.tracks` blocked apply for good.
 */
const ARTIFACTS = `
name: test
version: 1
artifacts:
  - id: proposal
    generates: proposal.md
    description: Proposal
    template: proposal.md
  - id: design
    generates: design.md
    description: Design
    template: design.md
    requires: [proposal]
  - id: tasks
    generates: tasks.md
    description: Tasks
    template: tasks.md
    requires: [proposal]
  - id: checklist
    generates: "work/*.md"
    description: Checklist
    template: checklist.md
    requires: [proposal]
`;

const withApply = (apply: string) => `${ARTIFACTS}apply:\n${apply}\n`;

function errorFrom(yaml: string): Error {
  try {
    parseSchema(yaml);
  } catch (error) {
    return error as Error;
  }
  throw new Error('expected parseSchema to throw');
}

describe('parseSchema apply references', () => {
  describe('apply.requires', () => {
    it('accepts ids the schema declares', () => {
      const schema = parseSchema(withApply('  requires: [design, tasks]\n  tracks: tasks.md'));
      expect(schema.apply?.requires).toEqual(['design', 'tasks']);
    });

    it('rejects an id no artifact declares, naming it and the declared ids', () => {
      const error = errorFrom(withApply('  requires: [desgin]'));
      expect(error).toBeInstanceOf(SchemaValidationError);
      expect(error.message).toContain(`Invalid apply.requires reference: 'desgin' does not exist`);
      expect(error.message).toContain('proposal, design, tasks, checklist');
    });

    it('rejects one unknown id among valid ones', () => {
      const error = errorFrom(withApply('  requires: [design, tsks]\n  tracks: tasks.md'));
      expect(error).toBeInstanceOf(SchemaValidationError);
      expect(error.message).toContain(`'tsks' does not exist`);
    });

    it('is case-sensitive, like artifact requires', () => {
      expect(() => parseSchema(withApply('  requires: [Tasks]'))).toThrow(
        /Invalid apply\.requires reference: 'Tasks'/
      );
    });
  });

  describe('apply.tracks', () => {
    it('accepts the generates path of a declared artifact', () => {
      const schema = parseSchema(withApply('  requires: [tasks]\n  tracks: tasks.md'));
      expect(schema.apply?.tracks).toBe('tasks.md');
    });

    it('accepts a glob generates repeated verbatim', () => {
      const schema = parseSchema(withApply('  requires: [checklist]\n  tracks: "work/*.md"'));
      expect(schema.apply?.tracks).toBe('work/*.md');
    });

    it('accepts an apply block that tracks nothing', () => {
      expect(() => parseSchema(withApply('  requires: [tasks]'))).not.toThrow();
      expect(() => parseSchema(withApply('  requires: [tasks]\n  tracks: null'))).not.toThrow();
    });

    it('rejects a path no artifact generates, naming it', () => {
      const error = errorFrom(withApply('  requires: [tasks]\n  tracks: task.md'));
      expect(error).toBeInstanceOf(SchemaValidationError);
      expect(error.message).toContain(
        `Invalid apply.tracks path: 'task.md' is not generated by any artifact`
      );
      expect(error.message).toContain('tasks.md');
    });

    // The tracked-tasks lookups select the artifact whose `generates` equals
    // `tracks`, so a file that merely matches a glob, or another spelling of
    // the same path, resolves to no artifact at run time.
    it('rejects a single file that only matches a glob generates', () => {
      expect(() =>
        parseSchema(withApply('  requires: [checklist]\n  tracks: work/todo.md'))
      ).toThrow(/Invalid apply\.tracks path: 'work\/todo\.md'/);
    });

    it('rejects another spelling of a generated path', () => {
      expect(() => parseSchema(withApply('  requires: [tasks]\n  tracks: ./tasks.md'))).toThrow(
        /Invalid apply\.tracks path: '\.\/tasks\.md'/
      );
    });
  });

  it('accepts a schema with no apply block', () => {
    expect(parseSchema(ARTIFACTS).apply).toBeUndefined();
  });

  it('still parses every built-in schema', () => {
    const schemasDir = path.join(cliProjectRoot, 'schemas');
    const names = fs
      .readdirSync(schemasDir, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name);
    expect(names.length).toBeGreaterThan(0);
    for (const name of names) {
      const yaml = fs.readFileSync(path.join(schemasDir, name, 'schema.yaml'), 'utf-8');
      expect(() => parseSchema(yaml), name).not.toThrow();
    }
  });
});
